### PR TITLE
Fix incorrect mimetype inferrence

### LINKED ISSUE #8045: Send the file name with extension when sharing/opening to another app
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.804

### Where did you get the app from?

Google Play

### Android version

14

### Device model

_No response_

### Steps to reproduce

- Go to an email with a PDF attachment 
- Click it
- Open with a PDF viewer (google pdf viewer or GrapheneOS's PdfViewer)  (https://github.com/GrapheneOS/PdfViewer/issues/334)
- Click on share and use K-9 mail, write an email and notice the attached file has no extension

if you actually send the email thinking you attached a PDF, without any file extension the recipient will not be able to use it.

Maybe this is related to https://github.com/thunderbird/thunderbird-android/issues/2789

### Expected behavior

Have the .pdf extension

### Actual behavior

No extension

I actually thinked it was due to GrapheneOS's PdfViewer: https://github.com/GrapheneOS/PdfViewer/issues/334
But they said it is in K-9 mail and say it also can be reproduced by using google pdf viewer

### Logs

_No response_

### PR DESCRIPTION
**Pull request by Mino260806**
An android app must set the mime type correctly before opening an attachment so it opens with the right app. 
However, in the current implementation, K-9 checks the received mimetype from the server, if it's different from the default `application/octet-stream`, it tries to infer it from file extension. But I was able to find in my inbox emails where pdf files are tagged by default `text/plain` from the sender, what makes thunderbird open them as text, and thus any app will fail to open the file. 
Issue #8045 also describes the same problem.

As a result, this commit makes K-9 also treat `text/plain` as a default mimetype too, so it forces it to try infer the type automatically from file extension, what fixes the issue

------

Closes #8045

### CODE REVIEW

File: legacy/core/src/main/java/com/fsck/k9/helper/MimeTypeUtil.java [hunk 1]
```diff
@@ -8,6 +8,7 @@
 
 public class MimeTypeUtil {
     public static final String DEFAULT_ATTACHMENT_MIME_TYPE = "application/octet-stream";
+    public static final String PLAIN_TEXT_MIME_TYPE = "text/plain";
```
Comment (wmontwe) [inline legacy/core/src/main/java/com/fsck/k9/helper/MimeTypeUtil.java:11]: 👍

**Review by wmontwe — APPROVED** [review]
Tested and seems to work. Thank you!

**Comment by cketti** [comment]
The problem described in #8045 is different from the one that is addressed by this pull request. I tried to describe what is causing the problem in issue #8045 in [this comment](https://github.com/thunderbird/thunderbird-android/issues/8045#issuecomment-2302525934).

This change does what the pull request description says it does. However, emails that use the wrong MIME type (other than `application/octet-stream` that can be used as a fall-back when no concrete MIME type is known) for an attachment are broken. 

Email clients shouldn't try to be clever and silently "fix" this (Thunderbird on desktop doesn't). Doing this would just lead to more broken messages because people writing software to create such messages will often test the output of their software with a single email client and conclude they did it correctly because it's working with that one email client. If that happens often enough every email client has to implement this non-standard behavior to be compatible with message that can be found in the wild. Unfortunately, I've seen similar cases like this in the past. It's not just a theoretical problem.

So we're going to revert this change.

But even without this change you should still be able to open PDF attachments that use a MIME type of `text/plain` by saving the attachment first, then opening it using a file manager or the PDF viewer directly.
