### PR TITLE
Make Email Notifications On by Default

### LINKED ISSUE #8726: E-Mail Notifications should be default-ON
### Checklist

- [x] I have used the search function to see if someone else has already submitted the same bug report.
- [x] I will describe the problem with as much detail as possible.

### App

Thunderbird for Android

### App version

8.2

### Where did you get the app from?

F-Droid

### Android version

Android 14

### Device model

Xiaomi Poco F5

### Steps to reproduce

1. Import email accounts or add some manually. Any email account will do.
2. By default, notifications are OFF.

### Expected behavior

IMHO, notifications should be ON by default.
Why would I jump through all those hoops setting up multiple different email accounts on my phone only to be kept in the dark if a new mail has arrived?

### Actual behavior

After setup, all email notifications are OFF.

### Logs

_No response_

### PR DESCRIPTION
**Pull request by shamim-emon**
- Fixes #8726

### CODE REVIEW

**Comment by kewisch** [comment]
@shamim-emon What are your thoughts on the migration process here? What should happen to users who have not interacted with this setting and are used to notifications being off by default, who would now have it enabled on the upgrade?

**Comment by shamim-emon** [comment]
> @shamim-emon What are your thoughts on the migration process here? What should happen to users who have not interacted with this setting and are used to notifications being off by default, who would now have it enabled on the upgrade?

@kewisch how about one time in-app prompt stating the fact that this setting is enabled and an option to turn this setting off?

**Comment by kewisch** [comment]
I'm a little bit cautious on in-app prompting, it can get in the way and if we have multiple such upgrades to run for e.g. users who haven't updated in a while, we might create a bunch of prompts. 

If we were to prompt on upgrade, we'd probably need a more elaborate mechanism that will allow us to centrally register migrations the user can decide on, and show that prompt once on upgrade. This would be overkill for just this issue though and we'd need to involve design on how that would look.

What about something a little more subtle? Is there any logic we could use that wouldn't be a surprise to users, maybe without a prompt?

**Comment by shamim-emon** [comment]
> I'm a little bit cautious on in-app prompting, it can get in the way and if we have multiple such upgrades to run for e.g. users who haven't updated in a while, we might create a bunch of prompts.
> 
> If we were to prompt on upgrade, we'd probably need a more elaborate mechanism that will allow us to centrally register migrations the user can decide on, and show that prompt once on upgrade. This would be overkill for just this issue though and we'd need to involve design on how that would look.
> 
> What about something a little more subtle? Is there any logic we could use that wouldn't be a surprise to users, maybe without a prompt?

@kewisch how about` Soft Nudges` then? Like a  one time toast/snack-bar message when they open the app, like "You can now receive email notifications for important updates. Manage settings anytime."? Does that sound reasonable?

**Comment by kewisch** [comment]
I think it would suffer the same problem: Imagine you did an upgrade after 10 versions and got 11 soft nudges (one because our future selves forgot we already did one that release). It might also be a possibility to do something without user interaction.

**Comment by shamim-emon** [comment]
> I think it would suffer the same problem: Imagine you did an upgrade after 10 versions and got 11 soft nudges (one because our future selves forgot we already did one that release). It might also be a possibility to do something without user interaction.

@kewisch How about we make email notification default conditional? Like it'd would depend on secondary flag? That flag would be false by default. It'd be only true if any account goes through on-boarding flow? 
Let me know if this is something we can go with? Or do you have any alternate suggestion in mind?

**Comment by kewisch** [comment]
The least magic approach would be:
* If they have not set the flag prior, it gets explicitly set to false because this was the prior default. We do this as a migration.
* If they have set the flag to either true or false it stays the way it is
* If no accounts exist then they will get the implicit new default of true when the account is created, no explicit setting.

The downside here is that with that migration, we have no indicator if they have previously set the notifications or not, so if we later decide to tell users they can enable notifications, we don't know if they made a choice or not.

It might be worth looking if there is some indicator we have they went through the QR code import flow, in which case we might want to not set to false explicitly but instead keep the implied true.

The next thing I would do (that I have not) would be to determine how they previously ended up with the implicit false choice, and if it would be a surprise for them if notifications were on. We could also consider running an experiment on beta where we just default to true like you have, with no migration, and see what the feedback is.

I'm intentionally not making a decision here because I'd like to have your opinion. Given these constraints, what do you think would best serve the user?

**Comment by shamim-emon** [comment]
> The least magic approach would be:
> 
> * If they have not set the flag prior, it gets explicitly set to false because this was the prior default. We do this as a migration.
> * If they have set the flag to either true or false it stays the way it is
> * If no accounts exist then they will get the implicit new default of true when the account is created, no explicit setting.
> 
> The downside here is that with that migration, we have no indicator if they have previously set the notifications or not, so if we later decide to tell users they can enable notifications, we don't know if they made a choice or not.
> 
> It might be worth looking if there is some indicator we have they went through the QR code import flow, in which case we might want to not set to false explicitly but instead keep the implied true.
> 
> The next thing I would do (that I have not) would be to determine how they previously ended up with the implicit false choice, and if it would be a surprise for them if notifications were on. We could also consider running an experiment on beta where we just default to true like you have, with no migration, and see what the feedback is.
> 
> I'm intentionally not making a decision here because I'd like to have your opinion. Given these constraints, what do you think would best serve the user?

@kewisch IMO ` We could also consider running an experiment on beta where we just default to true like you have, with no migration, and see what the feedback is.`  is  a good suggestion and would like to move forward with it.

**Comment by shamim-emon** [comment]
@kewisch @wmontwe added corresponding default values under Feature flag, please let me know if that's alright or you'd prefer any alteration. Thanks

**Comment by kewisch** [comment]
@shamim-emon I might be in over my head on this review. I looked at https://github.com/thunderbird/thunderbird-android/pull/8650/files where a feature flag was added and there are a few more changes to ensure the flag is enabled on daily+debug, in our case should also be enabled on beta, but disabled on release. Would we need something like that as well?

**Comment by shamim-emon** [comment]
> @shamim-emon I might be in over my head on this review. I looked at https://github.com/thunderbird/thunderbird-android/pull/8650/files where a feature flag was added and there are a few more changes to ensure the flag is enabled on daily+debug, in our case should also be enabled on beta, but disabled on release. Would we need something like that as well?

@kewisch just did this in this [PR](https://github.com/thunderbird/thunderbird-android/pull/8958) . Will also do it here. I have created another [PR](https://github.com/thunderbird/thunderbird-android/pull/8967) aiming to add more flexibility around feature flag handling. Once there's a decision on it, I will be able to move forward with your suggestion here.

**Comment by shamim-emon** [comment]
@kewisch @wmontwe updated the default under feature flag and enabled/disabled flag based on build type. Please let me know if anything else is required. Thanks

**Comment by kewisch** [comment]
Thanks @shamim-emon ! Wolf will take a look soon.

File: legacy/account/src/main/java/app/k9mail/legacy/account/Account.kt [hunk 1]
```diff
@@ -17,6 +19,7 @@ const val DEFAULT_VISIBLE_LIMIT = 25
 class Account(
     override val uuid: String,
     private val isSensitiveDebugLoggingEnabled: () -> Boolean = { false },
+    private val featureFlagProvider: FeatureFlagProvider,
```
Comment (wmontwe) [inline legacy/account/src/main/java/app/k9mail/legacy/account/Account.kt:22]: I think the `FeatureFlagProvider` should not be used here. Instead I suggest wrapping it in a `AccountDefaultsProvider` that encapsulates the account from the `FeatureFlagProvider`. And apply the changes after the account has been loaded (`accountPreferenceSerializer.loadAccount(account, storage)`) as part of the `AccountManager/Preferences`

```kotlin
package app.k9mail.legacy.account

fun interface AccountDefaultsProvider {
    fun applyDefaults(account: Account)
}
```

and in the `app-common` module (I added a pull-reques as support #8988):

```kotlin
package net.thunderbird.app.common.account

class CommonAccountDefaultsProvider(
    private val featureFlagProvider: FeatureFlagProvider,
) : AccountDefaultsProvider {

    override fun applyDefaults(account: Account) {
        account.isNotifyNewMail = featureFlagProvider.provide(
            "email_notification_default".toFeatureFlagKey(),
        ).whenEnabledOrNot(
            onEnabled = { true },
            onDisabledOrUnavailable = { false },
        )

        account.isNotifySelfNewMail = featureFlagProvider.provide(
            "email_notification_default".toFeatureFlagKey(),
        ).whenEnabledOrNot(
            onEnabled = { true },
            onDisabledOrUnavailable = { false },
        )
    }
}
```

File: legacy/account/src/main/java/app/k9mail/legacy/account/Account.kt [hunk 2]
```diff
@@ -80,15 +83,25 @@ class Account(
 
     @get:Synchronized
     @set:Synchronized
-    var isNotifyNewMail = false
+    var isNotifyNewMail = featureFlagProvider.provide(
```
Comment (wmontwe) [inline legacy/account/src/main/java/app/k9mail/legacy/account/Account.kt:86]: This is not necessary

File: legacy/account/src/main/java/app/k9mail/legacy/account/Account.kt [hunk 3]
```diff
@@ -80,15 +83,25 @@ class Account(
...
+    )
 
     @get:Synchronized
     @set:Synchronized
     var folderNotifyNewMailMode = FolderMode.ALL
 
     @get:Synchronized
     @set:Synchronized
-    var isNotifySelfNewMail = false
+    var isNotifySelfNewMail = featureFlagProvider.provide(
```
Comment (wmontwe) [inline legacy/account/src/main/java/app/k9mail/legacy/account/Account.kt:99]: This is not necessary

**Review by wmontwe — CHANGES_REQUESTED** [review]
Thank you, I propose a different approach instead of including the feature flags in the account object.

File: legacy/account/src/main/java/app/k9mail/legacy/account/Account.kt (hunk 1 above)
Comment (shamim-emon) [reply legacy/account/src/main/java/app/k9mail/legacy/account/Account.kt]: @wmontwe Done!

File: legacy/account/src/main/java/app/k9mail/legacy/account/Account.kt (hunk 2 above)
Comment (shamim-emon) [reply legacy/account/src/main/java/app/k9mail/legacy/account/Account.kt]: Reverted!

File: legacy/account/src/main/java/app/k9mail/legacy/account/Account.kt (hunk 3 above)
Comment (shamim-emon) [reply legacy/account/src/main/java/app/k9mail/legacy/account/Account.kt]: Reverted!

File: legacy/core/src/main/java/com/fsck/k9/AccountPreferenceSerializer.kt [hunk 4]
```diff
@@ -24,9 +26,11 @@ import com.fsck.k9.preferences.Storage
 import com.fsck.k9.preferences.StorageEditor
 import timber.log.Timber
 
+@Suppress("MaxLineLength")
 class AccountPreferenceSerializer(
     private val resourceProvider: CoreResourceProvider,
     private val serverSettingsSerializer: ServerSettingsSerializer,
+    private val featureFlagProvider: FeatureFlagProvider,
```
[the remark this answers is not in the document]
Comment (shamim-emon) [reply legacy/core/src/main/java/com/fsck/k9/AccountPreferenceSerializer.kt]: Removed

File: legacy/core/src/main/java/com/fsck/k9/AccountPreferenceSerializer.kt [hunk 5]
```diff
@@ -52,7 +56,14 @@ class AccountPreferenceSerializer(
             if (displayCount < 0) {
                 displayCount = K9.DEFAULT_VISIBLE_LIMIT
             }
-            isNotifyNewMail = storage.getBoolean("$accountUuid.notifyNewMail", false)
+
```
[the remark this answers is not in the document]
Comment (shamim-emon) [reply legacy/core/src/main/java/com/fsck/k9/AccountPreferenceSerializer.kt]: Removed

File: legacy/account/build.gradle.kts [hunk 6]
```diff
@@ -11,4 +11,5 @@ dependencies {
     implementation(projects.legacy.notification)
     implementation(projects.mail.common)
     implementation(projects.backend.api)
+    implementation(projects.core.featureflags)
```
Comment (wmontwe) [inline legacy/account/build.gradle.kts:14]: This is not needed anymore

File: legacy/core/src/main/java/com/fsck/k9/AccountPreferenceSerializer.kt [hunk 7]
```diff
@@ -52,8 +52,6 @@ class AccountPreferenceSerializer(
             if (displayCount < 0) {
                 displayCount = K9.DEFAULT_VISIBLE_LIMIT
             }
-            isNotifyNewMail = storage.getBoolean("$accountUuid.notifyNewMail", false)
```
Comment (wmontwe) [inline legacy/core/src/main/java/com/fsck/k9/AccountPreferenceSerializer.kt:55]: This is still needed

**Review by wmontwe — CHANGES_REQUESTED** [review]
Looks good! Just two minor changes.

File: legacy/account/build.gradle.kts (hunk 6 above)
Comment (shamim-emon) [reply legacy/account/build.gradle.kts]: Removed!

File: legacy/core/src/main/java/com/fsck/k9/AccountPreferenceSerializer.kt (hunk 7 above)
Comment (shamim-emon) [reply legacy/core/src/main/java/com/fsck/k9/AccountPreferenceSerializer.kt:55]: Added back!

**Review by wmontwe — APPROVED** [review]
👍
