### PR TITLE
Fix account setup small screen rendering

### LINKED ISSUE #7146: new account setup in 6.710 has too small text input
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.710

### Where did you get the app from?

F-Droid

### Android version

8

### Device model

WAS-LX1

### Steps to reproduce

1. Start creation of new account
2. New screen with text input is shown
3. Start writing the email address 

### Expected behavior

The text input should be entirely visible and expand to fill all needed vertical space 

### Actual behavior

Screenshot_20230829-200651

The keyboard eats up most vertical space and the large header won't scroll to leave room for the text input.

Screenshot_20230829-200702

The address can be written even when the input is not visible and when the keyboard is closed it's perfectly aligned vertically.

### Logs

_No response_

### PR DESCRIPTION
**Pull request by wmontwe**
Changes the layout to work on small screens:

grafik

Fixes #7146

Depends on #7560

### CODE REVIEW

File: feature/account/setup/src/main/kotlin/app/k9mail/feature/account/setup/ui/autodiscovery/AccountAutoDiscoveryContent.kt [hunk 1]
```diff
@@ -1,80 +1,187 @@
...
 @Composable
 internal fun AccountAutoDiscoveryContent(
     state: State,
     onEvent: (Event) -> Unit,
     oAuthViewModel: AccountOAuthContract.ViewModel,
-    contentPadding: PaddingValues,
     modifier: Modifier = Modifier,
 ) {
-    ResponsiveWidthContainer(
+    Background(
```
Comment (cketti) [inline feature/account/setup/src/main/kotlin/app/k9mail/feature/account/setup/ui/autodiscovery/AccountAutoDiscoveryContent.kt:49]: [Optional] Using a background feels unnecessary. If the issue is that previews are not showing a background, we could use the `Background` composable there. Alternatively, we could use `@Preview` annotations with `showBackground = true`.

File: feature/account/setup/src/main/kotlin/app/k9mail/feature/account/setup/ui/autodiscovery/AccountAutoDiscoveryContent.kt [hunk 2]
```diff
@@ -1,80 +1,187 @@
...
             ) {
-                contentItems(
-                    state = state,
-                    onEvent = onEvent,
-                    oAuthViewModel = oAuthViewModel,
+                Column(
+                    modifier = Modifier
+                        .weight(1f)
+                        .verticalScroll(scrollState)
+                        .imePadding(),
```
Comment (cketti) [inline feature/account/setup/src/main/kotlin/app/k9mail/feature/account/setup/ui/autodiscovery/AccountAutoDiscoveryContent.kt:65]: [Optional] I don't think this is doing anything. `FeatureLauncherApp()` already consumes all window insets by using the `safeDrawingPadding()` modifier.

File: feature/account/setup/src/main/kotlin/app/k9mail/feature/account/setup/ui/autodiscovery/AccountAutoDiscoveryContent.kt [hunk 3]
```diff
@@ -1,80 +1,187 @@
...
+                ) {
+                    AppTitleTopHeader(
+                        title = stringResource(id = R.string.account_setup_title),
+                        modifier = Modifier
+                            .padding(
+                                start = MainTheme.spacings.double,
+                                end = MainTheme.spacings.double,
+                            ),
```
Comment (cketti) [inline feature/account/setup/src/main/kotlin/app/k9mail/feature/account/setup/ui/autodiscovery/AccountAutoDiscoveryContent.kt:73]: This is adding additional horizontal padding and leads to the header text now being two lines on my Pixel 2 when it previously was only one.

File: feature/account/setup/src/main/kotlin/app/k9mail/feature/account/setup/ui/autodiscovery/AutoDiscoveryStringMapper.kt [hunk 4]
```diff
@@ -2,12 +2,13 @@ package app.k9mail.feature.account.setup.ui.autodiscovery
...
 import android.content.res.Resources
 import app.k9mail.core.common.domain.usecase.validation.ValidationError
+import app.k9mail.feature.account.server.settings.domain.usecase.ValidatePassword
 import app.k9mail.feature.account.setup.R
 import app.k9mail.feature.account.setup.domain.entity.AutoDiscoveryConnectionSecurity
 import app.k9mail.feature.account.setup.domain.usecase.ValidateConfigurationApproval
 import app.k9mail.feature.account.setup.domain.usecase.ValidateEmailAddress
 
-internal fun AutoDiscoveryConnectionSecurity.toResourceString(resources: Resources): String {
+internal fun AutoDiscoveryConnectionSecurity.toAutoDiscoveryConnectionSecuriyString(resources: Resources): String {
```
Comment (cketti) [inline feature/account/setup/src/main/kotlin/app/k9mail/feature/account/setup/ui/autodiscovery/AutoDiscoveryStringMapper.kt:11]: Typo

```suggestion
internal fun AutoDiscoveryConnectionSecurity.toAutoDiscoveryConnectionSecurityString(resources: Resources): String {
```

File: feature/account/setup/src/main/kotlin/app/k9mail/feature/account/setup/ui/autodiscovery/AccountAutoDiscoveryContent.kt [hunk 5]
```diff
@@ -1,80 +1,187 @@
...
+
+@Composable
+internal fun ContentView(
+    state: State,
+    onEvent: (Event) -> Unit,
+    oAuthViewModel: AccountOAuthContract.ViewModel,
+    resources: Resources,
+    modifier: Modifier = Modifier,
+) {
+    Column(
```
Comment (cketti) [inline feature/account/setup/src/main/kotlin/app/k9mail/feature/account/setup/ui/autodiscovery/AccountAutoDiscoveryContent.kt:141]: [Optional] Instead of manually adding `Spacer` we could use `verticalArrangement = Arrangement.spacedBy(MainTheme.spacings.double)`

**Review by cketti — CHANGES_REQUESTED** [review]

File: feature/account/setup/src/main/kotlin/app/k9mail/feature/account/setup/ui/autodiscovery/AccountAutoDiscoveryContent.kt (hunk 5 above)
Comment (wmontwe) [reply feature/account/setup/src/main/kotlin/app/k9mail/feature/account/setup/ui/autodiscovery/AccountAutoDiscoveryContent.kt:141]: The UI doesn't use the same spacing for every element.

File: feature/account/setup/src/main/kotlin/app/k9mail/feature/account/setup/ui/autodiscovery/AccountAutoDiscoveryContent.kt (hunk 3 above)
Comment (wmontwe) [reply feature/account/setup/src/main/kotlin/app/k9mail/feature/account/setup/ui/autodiscovery/AccountAutoDiscoveryContent.kt:73]: There are sadly some variations of the header in the design. I think they need to be streamlined to do this properly.

Comment (wmontwe) [reply feature/account/setup/src/main/kotlin/app/k9mail/feature/account/setup/ui/autodiscovery/AccountAutoDiscoveryContent.kt:73]: Also the header breaks as soon the text is slightly longer

File: feature/account/setup/src/main/kotlin/app/k9mail/feature/account/setup/ui/autodiscovery/AccountAutoDiscoveryContent.kt (hunk 2 above)
Comment (wmontwe) [reply feature/account/setup/src/main/kotlin/app/k9mail/feature/account/setup/ui/autodiscovery/AccountAutoDiscoveryContent.kt:65]: With the removed scaffold that is true.

File: feature/account/setup/src/main/kotlin/app/k9mail/feature/account/setup/ui/autodiscovery/AccountAutoDiscoveryContent.kt (hunk 1 above)
Comment (wmontwe) [reply feature/account/setup/src/main/kotlin/app/k9mail/feature/account/setup/ui/autodiscovery/AccountAutoDiscoveryContent.kt:49]: That's true, I didn't alter the preview annotation, but I'll add one with background enabled now. Not need to add another `Background` composable then.

**Review by cketti — APPROVED** [review]
