### PR TITLE
Handle UTF8 strings sent using literal syntax

### LINKED ISSUE #9212: Non-english folder names are displayed incorrectly
### Checklist

- [x] I have used the search function to see if someone else has already submitted the same bug report.
- [x] I will describe the problem with as much detail as possible.

### App

K-9 Mail

### App version

Manually builded from branch main from 23.05.2025

### Where did you get the app from?

Other

### Android version

Android 14 HIOS (stock rom)

### Device model

Tecno Spark 30 (KL6)

### Steps to reproduce

1. Open app
2. Create account
3. Open folder list (left menu)
4. See "?" symbols instead of Cyrillic characters in folder names

### Expected behavior

Correct folder names, like this:

Image

### Actual behavior

Signs "?" instead of Cyrillic characters in folder names.

Image

### Logs

[k9mail-logs.txt](https://github.com/user-attachments/files/20417577/k9mail-logs.txt)

### PR DESCRIPTION
**Pull request by arnt**
RFC 6855/9755 permits IMAP servers to send UTF8 in strings such as "this", but does not ban sending literals such as {4}
this
instead, and some servers do, and #8772 did not handle that.

Fixes #9212

### CODE REVIEW

**Comment by ke46138** [comment]
Hmm. I built k9 and thunderbird from this pr, but the bug remains.

**Comment by arnt** [comment]
I would guess that's due to a weakness in IMAP: Clients have to cache folder names and guess how long to cache them. There's no mechanism to signal that a refresh is in order. The names will look wrong for a while, short or long. But again, that's guesswork.

But I'll test with my test phone on Monday, during normal working hours.

**Comment by arnt** [comment]
I'm running this PR now on a test phone. It's still using the cached folder name and will do so for at least half an hour (the value of `FOLDER_LIST_STALENESS_THRESHOLD`), not sure whether there are other conditions that may extend the cache lifetime. I'll just give it a few hours and see.

**Comment by ke46138** [comment]
I doubt it has anything to do with caching (if you uninstalled and installed thunderbird). I uninstalled thunderbird and installed the app I built from this pr, added an account and still the bug #9212 remains. _I remind you that the bug only appears if you uninstall and install the application (or if you delete the account and create it again), and if you haven't done that, thunderbird uses cached folder names and the bug doesn't appear._ I've been testing thunderbird for a few days.

**Comment by arnt** [comment]
You're right, all that the caching does is slow down my debugging. The mailbox name still wrong even after it issues the IMAP command that I think should fix it (the unit test I included in this PR is copied from a server log). I'll work on it again tomorrow.

**Comment by rafaeltonholo** [comment]
@arnt, the problem is in the `RealImapStore.getFolderDisplayName(serverId): String` method / `FolderNameCodec` class. The server is correctly returning the UTF-8 name (you can observe that via logcat). However, when we try to generate the folder display name, we mess up the encoding.

I guess that will help you with your debugging. Let me know if you need anything else 😊

**Comment by arnt** [comment]
That took a while, most of it trying to write a unit test. The worst part of my job is when I switch from one unit testing framework to another ;)

There were several things.
 - As @rafaeltonholo correctly noticed, `getFolderDisplayName()` is wrong, which confused me (it wasn't a problem when I first wrote this code — long story). Today's commit should fix that. Thanks @rafaeltonholo.
 - `createImapResponse()` couldn't support UTF8=ACCEPT, which today's commit fixes but I don't like the fix.
 - parsing folder names sent by the server as literals (instead of as strings) broke. This caused problems with servers that support UTF8=ACCEPT but avoid using it for output (which makes sense if the server's output code can't see the capabilities). The first commit fixes this.

**Review by rafaeltonholo — COMMENTED** [review]
Thank you for addressing the issue with folders containing UTF-8 characters not displaying correctly. However, the folder is still unusable when we attempt to perform any actions, such as moving a message to the UTF-8 folder. This is because it tries to use a `serverId` that is incorrectly encoded.

Although this issue has existed prior to this pull request, and I do not think it should prevent the merging of these changes, I would appreciate it if you could address this problem here, as it would simply require applying the same UTF-8 logic used in `getFolderDisplayName` to `getOldServerId`.

Let me know if you prefer addressing the `serverId` issue in another PR.

For future improvements: we need to reevaluate the `serverId` storage method and address the `TODO` comment in `CommandRefreshFolderList`.

**Comment by arnt** [comment]
Wat. I tested that. Can you name a specific folder name and server that broke?

I'm on vacation this week. I'll do my best *not* to work on this until I'm back (in seven days and a few hours from now). I'm extremely curious though.

**Comment by arnt** [comment]
Hm. I tested it with a branch that contains quite a bit more code than #8772.

**Comment by rafaeltonholo** [comment]
> Wat. I tested that. Can you name a specific folder name and server that broke?
> 
> I'm on vacation this week. I'll do my best _not_ to work on this until I'm back (in seven days and a few hours from now). I'm extremely curious though.

I have used the same name you have in one of your unit tests: `Исходящие`, but it also fails in all the following cases:
- `Ações`
- `Áêà`
- `Արխիվ`
- `أرشيف`
- `পুৰালেখ`
- `ⴰⵎⵢⴰⴳ`
- `ማህደር`
- `档案`

As you can see in the following screenshot, although the name is fixed, the `server_id` isn't, causing the issue of not being able to execute actions that are related to that folder.

image

---

For example, when trying to move a message from INBOX to Исходящие, the app moves the message locally (which is also wrong, but another issue) but fails to execute the move command in the remote:

```console
14:27:59.057 RealImapConnection      V  conn147206245>>> 17 UID MOVE 153 "?????????"
14:27:59.161 ImapResponseParser      V  conn147206245<<<#17# [NO, [TRYCREATE], The destination mailbox could not be found.]
14:27:59.172 MessagingController     E  Failure of command 'move_or_copy' was permanent, removing command
      com.fsck.k9.mail.store.imap.NegativeImapResponseException: Command: UID MOVE 153 "?????????"; response: #17# [NO, [TRYCREATE], The destination mailbox could not be found.]
      at com.fsck.k9.mail.store.imap.ImapResponseParser.readStatusResponse(ImapResponseParser.java:126)
      at com.fsck.k9.mail.store.imap.RealImapConnection.executeSimpleCommand(RealImapConnection.kt:742)
      at com.fsck.k9.mail.store.imap.RealImapConnection.executeSimpleCommand(RealImapConnection.kt:728)
      at com.fsck.k9.mail.store.imap.RealImapConnection.executeCommandWithIdSet(RealImapConnection.kt:765)
      at com.fsck.k9.mail.store.imap.RealImapFolder.moveMessagesUsingMoveExtension(RealImapFolder.kt:346)
      at com.fsck.k9.mail.store.imap.RealImapFolder.moveMessages(RealImapFolder.kt:327)
      at com.fsck.k9.backend.imap.CommandMoveOrCopyMessages.moveOrCopyMessages(CommandMoveOrCopyMessages.kt:59)
      at com.fsck.k9.backend.imap.CommandMoveOrCopyMessages.moveMessages(CommandMoveOrCopyMessages.kt:15)
      at com.fsck.k9.backend.imap.ImapBackend.moveMessages(ImapBackend.kt:96)
      at com.fsck.k9.controller.MessagingController.processPendingMoveOrCopy(MessagingController.java:921)
      at com.fsck.k9.controller.MessagingController.processPendingMoveOrCopy(MessagingController.java:885)
      at com.fsck.k9.controller.MessagingControllerCommands$PendingMoveOrCopy.execute(MessagingControllerCommands.java:67)
      at com.fsck.k9.controller.MessagingController.processPendingCommandsSynchronous(MessagingController.java:744)
      at com.fsck.k9.controller.MessagingController$3.run(MessagingController.java:714)
      at com.fsck.k9.controller.MessagingController.runInBackground(MessagingController.java:234)
      at com.fsck.k9.controller.MessagingController.-$$Nest$mrunInBackground(Unknown Source:0)
      at com.fsck.k9.controller.MessagingController$1.run(MessagingController.java:174)
      at java.lang.Thread.run(Thread.java:1012)
```

**Comment by arnt** [comment]
Have the bug fixed now. Wonder whether the code may have worked a while ago, but the corruption persisted via the LocalFolder database… anyway, I'll cut down the code to what's really necessary and submit an update tomorrow. The time is 21:45 here and the wise developer leaves the office.

**Comment by kewisch** [comment]
Thanks so much @arnt, really appreciate the persistence here!

**Comment by arnt** [comment]
But another working day has finished, I need to leave five minutes ago, and I still haven't send in the changed code. Need several hours to biject and be sure, and and that time is time I've spent in googledocs instead of here.

File: mail/protocols/imap/src/main/java/com/fsck/k9/mail/store/imap/FolderNameCodec.kt [hunk 1]
```diff
@@ -8,8 +8,13 @@ import java.nio.charset.StandardCharsets
 internal class FolderNameCodec {
     private val modifiedUtf7Charset = CharsetProvider().charsetForName("X-RFC-3501")
     private val asciiCharset = StandardCharsets.US_ASCII
+    private var utf8 = false
```
Comment (rafaeltonholo) [inline mail/protocols/imap/src/main/java/com/fsck/k9/mail/store/imap/FolderNameCodec.kt]: This property name is not descriptive enough. Please rename it to a more informative name. Additionally, consider making this property public since a setter method has been added to toggle it on or off.

```suggestion
    var acceptUtf8Encoding = false
```

File: mail/protocols/imap/src/main/java/com/fsck/k9/mail/store/imap/FolderNameCodec.kt [hunk 2]
```diff
@@ -8,8 +8,13 @@ import java.nio.charset.StandardCharsets
...
 
     fun encode(folderName: String): String {
+        if (utf8) {
```
Comment (rafaeltonholo) [inline mail/protocols/imap/src/main/java/com/fsck/k9/mail/store/imap/FolderNameCodec.kt]:
```suggestion
        if (acceptUtf8Encoding) {
```

File: mail/protocols/imap/src/main/java/com/fsck/k9/mail/store/imap/FolderNameCodec.kt [hunk 3]
```diff
@@ -18,10 +23,18 @@ internal class FolderNameCodec {
     }
 
     fun decode(encodedFolderName: String): String {
+        if (utf8) {
```
Comment (rafaeltonholo) [inline mail/protocols/imap/src/main/java/com/fsck/k9/mail/store/imap/FolderNameCodec.kt]:
```suggestion
        if (acceptUtf8Encoding) {
```

File: mail/protocols/imap/src/main/java/com/fsck/k9/mail/store/imap/FolderNameCodec.kt [hunk 4]
```diff
@@ -18,10 +23,18 @@ internal class FolderNameCodec {
...
         val decoder = modifiedUtf7Charset.newDecoder().onMalformedInput(CodingErrorAction.REPORT)
         val byteBuffer = ByteBuffer.wrap(encodedFolderName.toByteArray(asciiCharset))
         val charBuffer = decoder.decode(byteBuffer)
 
         return charBuffer.toString()
     }
+
+    fun setUtf8Accept(y: Boolean) {
+        utf8 = y
+    }
```
Comment (rafaeltonholo) [inline mail/protocols/imap/src/main/java/com/fsck/k9/mail/store/imap/FolderNameCodec.kt]: Unless you need a custom logic that isn't only a setter method, please use a Kotlin property instead.
```suggestion
```

File: mail/protocols/imap/src/main/java/com/fsck/k9/mail/store/imap/ImapConnection.kt [hunk 5]
```diff
@@ -19,6 +19,8 @@ internal interface ImapConnection {
 
     fun close()
 
+    fun canSendUTF8QuotedStrings(): Boolean
```
Comment (rafaeltonholo) [inline mail/protocols/imap/src/main/java/com/fsck/k9/mail/store/imap/ImapConnection.kt:22]: nit: As per Kotlin code conventions, for acronyms longer than two letters, we should capitalize only the first letter.
```diff
--    fun canSendUTF8QuotedStrings(): Boolean
++    fun canSendUtf8QuotedStrings(): Boolean
```

File: mail/protocols/imap/src/main/java/com/fsck/k9/mail/store/imap/ImapResponseParser.java [hunk 6]
```diff
@@ -22,14 +22,15 @@ class ImapResponseParser {
...
+    public ImapResponseParser(PeekableInputStream in, FolderNameCodec c) {
         this.inputStream = in;
         this.utf8Accept = false;
-        this.folderNameCodec = new FolderNameCodec();
+        this.folderNameCodec = c;
     }
 
     public void setUtf8Accepted(final boolean yes) {
         utf8Accept = yes;
+        folderNameCodec.setUtf8Accept(true);
```
Comment (rafaeltonholo) [inline mail/protocols/imap/src/main/java/com/fsck/k9/mail/store/imap/ImapResponseParser.java]: If you apply the property name change, and use the Kotlin Property:
```suggestion
        folderNameCodec.setAcceptUtf8Encoding(true);
```

File: mail/protocols/imap/src/main/java/com/fsck/k9/mail/store/imap/ImapResponseParser.java [hunk 7]
```diff
@@ -22,14 +22,15 @@ class ImapResponseParser {
     private boolean utf8Accept;
     private FolderNameCodec folderNameCodec;
 
-    public ImapResponseParser(PeekableInputStream in) {
+    public ImapResponseParser(PeekableInputStream in, FolderNameCodec c) {
         this.inputStream = in;
         this.utf8Accept = false;
-        this.folderNameCodec = new FolderNameCodec();
+        this.folderNameCodec = c;
```
Comment (rafaeltonholo) [inline mail/protocols/imap/src/main/java/com/fsck/k9/mail/store/imap/ImapResponseParser.java]: Please, avoid using single-letter variable names as they are not descriptive enough.

```suggestion
    public ImapResponseParser(PeekableInputStream in, FolderNameCodec folderNameCodec) {
        this.inputStream = in;
        this.utf8Accept = false;
        this.folderNameCodec = folderNameCodec;
```

File: mail/protocols/imap/src/test/java/com/fsck/k9/mail/store/imap/ImapResponseHelper.java [hunk 8]
```diff
@@ -21,9 +21,14 @@ public static List<ImapResponse> createImapResponseList(String... responses) thr
     }
 
     public static ImapResponse createImapResponse(String response) throws IOException {
+        return createImapResponse(response, false);
+    }
+
+    public static ImapResponse createImapResponse(String response, boolean utf8) throws IOException {
         String input = response + "\r\n";
         PeekableInputStream inputStream = new PeekableInputStream(new ByteArrayInputStream(input.getBytes()));
         ImapResponseParser parser = new ImapResponseParser(inputStream);
```
Comment (rafaeltonholo) [inline mail/protocols/imap/src/test/java/com/fsck/k9/mail/store/imap/ImapResponseHelper.java]: You missed adding the new constructor parameter for `ImapResponseParser`, which will cause a compilation error in the tests.
```suggestion
        ImapResponseParser parser = new ImapResponseParser(inputStream, new FolderNameCodec());
```

**Review by rafaeltonholo — CHANGES_REQUESTED** [review]
Hi @arnt,

Thank you for implementing the changes to address the issues I previously mentioned. Tested locally and all good!!

There are just a few comments and a compilation error that need to be resolved before we can merge the code.

Additionally, I kindly ask you to rebase your commits and apply our commits message format, available in the developer documentation: [Git Commit Guide > ✍️ Commit Message Format](https://thunderbird.github.io/thunderbird-android/docs/latest/contributing/git-commit-guide.html#-commit-message-format)

Great job on this matter! I truly appreciate your contributions and patience.

**Comment by rafaeltonholo** [comment]
Hi @arnt, have you had a chance to review the comments above?

File: mail/protocols/imap/src/test/java/com/fsck/k9/mail/store/imap/ImapResponseHelper.java (hunk 8 above)
Comment (rafaeltonholo) [reply mail/protocols/imap/src/test/java/com/fsck/k9/mail/store/imap/ImapResponseHelper.java]: Hi @arnt , this is still causing a compilation error, could you please fix that?

If you don't have enough time, I can also provide the fix to help. We would like to uplift this PR to beta as soon as possible

**Comment by arnt** [comment]
Sorry about the latency. I ran out of headspace, there's a limit to how many programming languages, testing frameworks etc I can handle at the same time.

I don't understand when 'gradle testFullDailyUnitTest' runs all tests and when it doesn't. I rebased and now it shows some errors that I didn't see when I wrote the code. I'll deal with them now.

**Review by rafaeltonholo — APPROVED** [review]
LGTM! Thanks for the contribution to our project and your patience addressing all the comments!

**Review by kewisch — APPROVED** [review]

**Comment by rafaeltonholo** [comment]
Hi @arnt, a unit test is failing. Can you fix it, or would you like me to resolve it so we can merge the changes?

**Comment by arnt** [comment]
Oops, I misread and didn't notice that. I get many unit test failures, all except one mention that `lateinit property logger has not been been initialized` and I didn't notice that there's an error has a different cause.

Let me look now.

BTW I'm not patient ­— you are.

**Comment by arnt** [comment]
The unit test failure appears to be a bug in the unit test. It needs to do a little more mocking. I'm unlikely to get to it tonight, but perhaps during the weekend.

**Comment by rafaeltonholo** [comment]
Hi @arnt, looks like there is a disconnection between what you are mocking in the unit test and what the method does itself.

In the test case, you are mocking the canSendUTF8QuotedStrings() function to return `true`, however, the method itself never uses that function, but relies on the `FolderNameCode.acceptUtf8Encoding` property to encode or not the folder's name.

**Comment by arnt** [comment]
Hi,

I found out that at the same time, fixed it, and pushed just now. Getting the code to compile on my 16GB laptop was bothersome, so I have not been able to test this on a real device. The unit tests pass (except for the `lateinit` errors, which seem unrelated to my code).

The code now assumes that if Thunderbird has several IMAP connections to the server, then they have the same capabilities. I'm not 100% sure, but I think I saw a similar assumption elsewhere.

**Comment by rafaeltonholo** [comment]
Thank you for this contribution!

**Comment by coreycb** [comment]
Hi, This is a large patch that I think could use some time on daily before we uplift. We can cut another beta next Monday and include this if testing goes well on daily. For now, I'm going to remove the beta uplift label.

**Comment by pagebug** [comment]
https://github.com/thunderbird/thunderbird-android/releases/tag/THUNDERBIRD_12_0b2
Where is the APK file?
image
image

**Comment by coreycb** [comment]
@pagebug I failed to push uplifts for 12.0b2 so there's nothing new in it. There's a 12.0b3 with uplifts and release notes. We don't have this UTF-8 fix in beta yet. We're aiming for getting it into 12.0b4 next Monday.
