### PR TITLE
Fix: Reduce logo size and ensure it resizes dynamically and fits all screen sizes

### LINKED ISSUE #8458: Welcome / Get started screen has vertical content overflow
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App

Thunderbird for Android

### App version

8.0

### Where did you get the app from?

Google Play

### Android version

8.0.0

### Device model

Asus Zenphone 3 Zoom (ZE553KL)

### Steps to reproduce

1. Install app for the first time or clear app data
2. Open Thunderbird
3. Try scrolling?

I was suggested to check my font and accessibility settings, and they're all still the default.

### Expected behavior

This is my opinion, but I would expect no content (text, in this case) to be going beyond any screen edge on the very first screen of an app, especially with visible clipping. I feel that scrolling should not be a thing, here.

No functionality is affected, this a purely esthetical matter. If this isn't a real issue, feel free to close it.

### Actual behavior

The bottom text ("Developed by a dedicated team at MZLA...") is slightly clipped and, together with the padding below, makes it so you can scroll up and down on the first screen, even though it's practically useless. Style points may be awarded for triggering the scroll-limit animations.

|tb81|tb82|tb83|
|-|-|-|

I tested the most recent beta on the Play Store (8.0b5) to see if it was any different. Instead of clipping and slightly overflowing, the text is buried beyond the bottom of the screen and unnoticeable unless the user scrolls down on their own initiative.

|tb-beta|tb-betb|
|-|-|

That seems wrong, but in a different sense. I don't know whether this change was intentional or not, given that the text is different (Thunderbird vs. Thunderbird Beta).

### Logs

_No response_

### PR DESCRIPTION
**Pull request by SttApollo**
Fixes #8458

### Description
This PR addresses #8458 where the logo on the onboarding screen flattened the text below. The `WelcomeLogo` composable has been updated to ensure dynamic resizing using `BoxWithConstraints` ensuring that the logo scales proportionally based on screen dimensions and fits properly without overlapping or pushing other components off-screen.

### Changes Made
- Updated `WelcomeLogo` to use `BoxWithConstraints` for adaptive sizing.
- Limited logo and circle sizes to a maximum based on screen width.
- Ensured `LazyColumnWithHeaderFooter` components are unaffected by the logo's size.
- Verified compatibility across various screen sizes (small, medium, large, and tablets).

### Testing
- Tested on multiple screen sizes to ensure no scrolling is required and all components fit properly.

### Visual Example
Screenshot 2024-12-29 at 3 33 02 PM
Screenshot 2024-12-29 at 3 28 56 PM
Screenshot 2024-12-29 at 3 29 19 PM

### CODE REVIEW

**Review by wmontwe — COMMENTED** [review]
@SttApollo This implementation reduces the logo size across all screen sizes, which diverges from the original design intention of making it prominent. To fix this, I suggest two changes:

1. Slighlty reduce the logo size from its original values to have more room in general.
2. Only use the shrinking logic when a certain maxWidth threshold is reached.

Given the impracticality of fitting all page elements on every screen size, especially very small phones and in landscape mode, I think it would be more effective to use a scroll indicator in these cases.

**Comment by SttApollo** [comment]
Hii @wmontwe - thank you for your patience. I slightly reduced the logo size and added a custom scroll indicator ( I couldn't find it in the project files and wasn't sure if I could add additional libraries). 

Below are additional notes, brief screen recordings and screenshots to explain this implementation. Please let me know your thoughts and I'll adjust accordingly again, as needed. 

- Custom Scroll indicator caches item  heights using onGloballyPositioned for accurate scroll behavior 
- Inserted a spacer at index=3, ensuring small phones register sufficient overflow for the scrollbar logic to prevent situations where the footer is just slightly cut off from the screen (noticed that issue when testing on smaller devices)
- Maintained vertical space evenly design [
Screenshot 2025-02-06 at 3 33 52 PM
Screenshot 2025-02-06 at 11 05 44 AM
SmallPhonee
[Pixel3.webm](https://github.com/user-attachments/assets/36a5fefd-9cc0-4046-b0b9-3fea42858b63)
[Pixel9ProXL.webm](https://github.com/user-attachments/assets/c3597091-cc13-4e63-9881-0144b9bf4a4f)
](url)

**Comment by SttApollo** [comment]
Hi @wmontwe! I was trying to make sure the commit passes detekt, so I moved the scroll indicator function to a different file and shortened the welcome content. Do you want me to keep working on these changes or revert to the last commit state?

**Comment by wmontwe** [comment]
@SttApollo I rebased the pull-request on the latest version of main.

I tried the solution, but I see some performance issues with the scroll indicator that causes compose to redraw a lot. 

I checked if there is another solution available, but not really. Worst case without the indicator, but I would like to look into it a bit.

**Comment by SttApollo** [comment]
> @SttApollo I rebased the pull-request on the latest version of main.
> 
> I tried the solution, but I see some performance issues with the scroll indicator that causes compose to redraw a lot.
> 
> I checked if there is another solution available, but not really. Worst case without the indicator, but I would like to look into it a bit.

Sounds good - I'll hold until further. Perhaps, I can look at other bugs I can be assigned to.

**Comment by kewisch** [comment]
@wmontwe any updates on this? I know you've been out a bit, when you have a chance to get back to it I'd appreciate!

**Comment by wmontwe** [comment]
@SttApollo Unfortunately, my attempts to enhance the scroll indicator were unsuccessful. It seems this requires significant efforts and should be a separate task.

I think it's best to remove it for now and I have a look at the version without scroll indicator.

> Sounds good - I'll hold until further. Perhaps, I can look at other bugs I can be assigned to.

Is there a specific area of interest (UI etc)?

**Comment by SttApollo** [comment]
I have removed the scroll indicator @wmontwe. And yes the UI for my first few issues! Is there anything in [#8812](https://github.com/thunderbird/thunderbird-android/issues/8812) epic I may be able to support? Also open to other suggestions you may have!

File: feature/onboarding/welcome/src/main/kotlin/app/k9mail/feature/onboarding/welcome/ui/WelcomeContent.kt [hunk 1]
```diff
@@ -1,5 +1,6 @@
 package app.k9mail.feature.onboarding.welcome.ui
 
+
```
Comment (wmontwe) [inline feature/onboarding/welcome/src/main/kotlin/app/k9mail/feature/onboarding/welcome/ui/WelcomeContent.kt:3]: I guess your using a different code format. Just run `./gradlew spotlessApply` to streamline your changes with our code format. If you update the branch to current main, Spotless is also way quicker.

File: feature/onboarding/welcome/src/main/kotlin/app/k9mail/feature/onboarding/welcome/ui/WelcomeContent.kt [hunk 2]
```diff
@@ -43,47 +46,51 @@ internal fun WelcomeContent(
...
+                            showImportButton = showImportButton,
+                            onStartClick = onStartClick,
+                            onImportClick = onImportClick,
+                        )
+                    },
+                    content = {
+                        item {WelcomeTitleItem(title = appName)}
+                        item {WelcomeMessageItem()}
+                    },
+                )
```
Comment (wmontwe) [inline feature/onboarding/welcome/src/main/kotlin/app/k9mail/feature/onboarding/welcome/ui/WelcomeContent.kt:69]: The box is not needed and instead the `fillMaxSize` should be applied to the `LazyColumnWithHeaderFooter`. The `WelcomeTitleItem` should move into the header section to group logo and title together.

```suggestion
    Surface(
        modifier = modifier,
    ) {
        ResponsiveContent {
            LazyColumnWithHeaderFooter(
                modifier = Modifier.fillMaxSize(),
                verticalArrangement = Arrangement.SpaceEvenly,
                header = {
                    WelcomeHeaderSection(title = appName)
                },
                footer = {
                    WelcomeFooterSection(
                        showImportButton = showImportButton,
                        onStartClick = onStartClick,
                        onImportClick = onImportClick,
                    )
                },
                content = {
                    item { WelcomeMessageItem() }
                },
            )
```

File: feature/onboarding/welcome/src/main/kotlin/app/k9mail/feature/onboarding/welcome/ui/WelcomeContent.kt [hunk 3]
```diff
@@ -43,47 +46,51 @@ internal fun WelcomeContent(
...
+
+
+
         }
     }
 }
 
+@Composable
+private fun WelcomeHeaderSection(
+
```
Comment (wmontwe) [inline feature/onboarding/welcome/src/main/kotlin/app/k9mail/feature/onboarding/welcome/ui/WelcomeContent.kt:80]: We always add the Modifier to composables. The title could be added here.

```suggestion
    title: String,
    modifier: Modifier = Modifier,
```

File: feature/onboarding/welcome/src/main/kotlin/app/k9mail/feature/onboarding/welcome/ui/WelcomeContent.kt [hunk 4]
```diff
@@ -43,47 +46,51 @@ internal fun WelcomeContent(
...
+){
+    Box(
+        modifier = Modifier
+            .fillMaxWidth()
+            .defaultItemModifier()
+            .padding(top = MainTheme.spacings.double),
+            contentAlignment = Alignment.Center,
+    ) {
+        WelcomeLogo()
```
Comment (wmontwe) [inline feature/onboarding/welcome/src/main/kotlin/app/k9mail/feature/onboarding/welcome/ui/WelcomeContent.kt:89]: Add the title here.

```suggestion
        WelcomeLogo()
        WelcomeTitleItem(title = title)
```

File: feature/onboarding/welcome/src/main/kotlin/app/k9mail/feature/onboarding/welcome/ui/WelcomeContent.kt [hunk 5]
```diff
@@ -43,47 +46,51 @@ internal fun WelcomeContent(
...
+@Composable
+private fun WelcomeHeaderSection(
+
+){
+    Box(
+        modifier = Modifier
+            .fillMaxWidth()
+            .defaultItemModifier()
+            .padding(top = MainTheme.spacings.double),
+            contentAlignment = Alignment.Center,
```
Comment (wmontwe) [inline feature/onboarding/welcome/src/main/kotlin/app/k9mail/feature/onboarding/welcome/ui/WelcomeContent.kt:87]: Replace the box by a column.
```suggestion
    Column(
        modifier = modifier
            .fillMaxWidth()
            .defaultItemModifier()
            .padding(top = MainTheme.spacings.double),
            contentAlignment = Alignment.Center,
            .padding(top = MainTheme.spacings.quadruple),
        verticalArrangement = Arrangement.spacedBy(MainTheme.spacings.double),
        horizontalAlignment = Alignment.CenterHorizontally,
```

File: feature/onboarding/welcome/src/main/kotlin/app/k9mail/feature/onboarding/welcome/ui/WelcomeContent.kt [hunk 6]
```diff
@@ -109,6 +116,23 @@ private fun WelcomeLogo(
     }
 }
 
+
+@Composable
+private fun WelcomeTitleItem(
+    title: String,
```
Comment (wmontwe) [inline feature/onboarding/welcome/src/main/kotlin/app/k9mail/feature/onboarding/welcome/ui/WelcomeContent.kt:122]: Please add the modifier here:

```suggestion
    title: String,
    modifier: Modifier = Modifier,
```

File: feature/onboarding/welcome/src/main/kotlin/app/k9mail/feature/onboarding/welcome/ui/WelcomeContent.kt [hunk 7]
```diff
@@ -109,6 +116,23 @@ private fun WelcomeLogo(
...
+) {
+    Box(
+        modifier = Modifier
```
Comment (wmontwe) [inline feature/onboarding/welcome/src/main/kotlin/app/k9mail/feature/onboarding/welcome/ui/WelcomeContent.kt:125]:
```suggestion
        modifier = modifier
```

File: feature/onboarding/welcome/src/main/kotlin/app/k9mail/feature/onboarding/welcome/ui/WelcomeContent.kt [hunk 8]
```diff
@@ -125,6 +149,20 @@ private fun WelcomeTitle(
     }
 }
 
+@Composable
+private fun WelcomeMessageItem(
+){
```
Comment (wmontwe) [inline feature/onboarding/welcome/src/main/kotlin/app/k9mail/feature/onboarding/welcome/ui/WelcomeContent.kt:154]: Please add the modifier here:

```suggestion
    modifier: Modifier = Modifier,
) {
```

**Review by wmontwe — CHANGES_REQUESTED** [review]
I think the size changes are working very good. Just the logo and title should be part of the header section. The Box around the layout is not needed, as it prevents the list to draw it's content to full screen size.

You could fix the formatting issues by running `./gradlew spotlessApply`. Run `./gradlew detekt` to find other issues.

**Comment by SttApollo** [comment]
@wmontwe thank you, done!

**Review by wmontwe — APPROVED** [review]
Thank you!
