### PR TITLE
Fix a crash that occurs when the password input field visibility state changes and an accessibility service is enabled running Android 7 (API level 25) and below

### LINKED ISSUE #7705: Crash when unmasking a password field (v. 6.800 from GitHub)
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

GitHub

### Where did you get the app from?

Other

### Android version

7.0 MIUI 11

### Device model

Xiaomi Redmi Note 4

### Steps to reproduce

Settings --> Account settings --> Fetching mail --> Incoming server --> Password unhide

### Expected behavior

No crashes like before

### Actual behavior

Crash when unmasking a password field.

### Logs

[k9mail-logs.txt](https://github.com/thunderbird/thunderbird-android/files/14535855/k9mail-logs.txt)

### PR DESCRIPTION
**Pull request by muqeeta96**
This pull request addresses a critical issue: our app crashes when the password visibility state changes while an accessibility service is enabled, particularly on devices running Android 7 (API level 25) and below. The crash stems from an interaction between accessibility services and Jetpack Compose and how these components handle accessibility events.

This issue is documented in ticket #7705, and it has also been recognized as a broader issue on Google's end, as detailed in this [Google Issue Tracker](https://issuetracker.google.com/issues/348232635).

Fixes  #7705

### CODE REVIEW

**Review by cketti — CHANGES_REQUESTED** [review]
Thanks for working on this :heart: 

In my tests the app didn't crash on Android 8 and above. So I think this work-around can be limited to Android 7 (and below, since I wasn't able to get Talkback working in emulators prior to Android 7.1).

Unfortunately, this change currently only fixes the password input in the server settings screens. It doesn't fix the password input in the automatic account setup flow. The work-around should probably be moved further down. I think the `TextFieldOutlinedPassword` implementations are a good place for it.

**Comment by muqeeta96** [comment]
Ok. I will make the changes today.

File: core/ui/compose/designsystem/src/main/kotlin/app/k9mail/core/ui/compose/designsystem/atom/textfield/TextFieldOutlinedPassword.kt [hunk 1]
```diff
@@ -129,3 +132,16 @@ private fun selectVisualTransformation(
 }
 
 private fun isShowPasswordAllowed(isEnabled: Boolean, isPasswordVisible: Boolean) = isEnabled && isPasswordVisible
+
+private fun Modifier.applyLegacyPasswordSemantics(): Modifier {
+    /*
+    * Workaround to fix a crash that occurs when the password visibility state changes
+    * and an accessibility service is enabled. It prevents the crash by clearing and
+    * resetting the semantics of the composable.
```
Comment (cketti) [inline core/ui/compose/designsystem/src/main/kotlin/app/k9mail/core/ui/compose/designsystem/atom/textfield/TextFieldOutlinedPassword.kt:140]: The comment needs to be updated to reflect the new code. It should probably also include a link to the relevant Google issue: https://issuetracker.google.com/issues/348232635

**Review by cketti — CHANGES_REQUESTED** [review]
Thanks for updating the pull request :+1: 

There's some [code style violations](https://github.com/thunderbird/thunderbird-android/actions/runs/10529394461/job/29198576672?pr=8071#step:6:57). You should be able to automatically fix them using `gradlew spotlessApply`.

Please rewrite the history of your branch to be based on the current state of the `main` branch and only contains one commit with your change. This will make it easier for us to merge your change. If you need help with that, please let me know.

**Comment by muqeeta96** [comment]
I mistakenly merge it. But now I fixed it with a rebase and pushed it.

**Comment by cketti** [comment]
Thank you :+1:
