### PR TITLE
Fix account could be null when deleted

### LINKED ISSUE #9190: Drawer - Crash when selecting folder
Google play reported crash on 11.0b2. So far not reproducible.

```
Exception java.lang.NullPointerException:
  at com.fsck.k9.activity.MessageList.configureDrawer (MessageList.kt:1464)
  at com.fsck.k9.activity.MessageList.initializeFromLocalSearch (MessageList.kt:1438)
  at com.fsck.k9.activity.MessageList.performSearch (MessageList.kt:749)
  at com.fsck.k9.activity.MessageList.openFolder (MessageList.kt:703)
  at com.fsck.k9.activity.MessageList.initializeFolderDrawer$lambda$22$lambda$17 (MessageList.kt:653)
  at net.thunderbird.feature.navigation.drawer.dropdown.ui.DrawerViewKt$DrawerView$$inlined$observe$2$1.emit (UnidirectionalViewModel.kt:99)
  at kotlinx.coroutines.flow.SharedFlowImpl.collect$suspendImpl (SharedFlow.kt:397)
  at kotlinx.coroutines.flow.SharedFlowImpl$collect$1.invokeSuspend (SharedFlow.kt)
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (ContinuationImpl.kt:33)
  at kotlinx.coroutines.DispatchedTask.run (DispatchedTask.kt:100)
  at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch (AndroidUiDispatcher.android.kt:79)
  at androidx.compose.ui.platform.AndroidUiDispatcher.access$setScheduledFrameDispatch$p (AndroidUiDispatcher.android.kt:41)
  at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch (AndroidUiDispatcher.android.kt:41)
  at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run (AndroidUiDispatcher.android.kt:57)
  at android.os.Handler.handleCallback (Handler.java:1001)
  at android.os.Handler.dispatchMessage (Handler.java:105)
  at android.os.Looper.loopOnce (Looper.java:268)
  at android.os.Looper.loop (Looper.java:384)
  at android.app.ActivityThread.main (ActivityThread.java:8936)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:580)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:907)
```

### PR DESCRIPTION
**Pull request by wmontwe**
This might fix the crash, but as I can't reproduce the crash it's just hardening the logic to perform searches and update the local account instance.

Fixes #9190

### CODE REVIEW

File: legacy/ui/legacy/src/main/java/com/fsck/k9/activity/MessageList.kt [hunk 1]
```diff
@@ -1437,6 +1437,10 @@ open class MessageList :
             } else {
                 account = null
             }
+        } else {
+            if (account == null && search.accountUuids.size == 1) {
+                account = accountManager.getAccount(search.accountUuids[0])
+            }
         }
 
         configureDrawer()
```
Comment (kewisch) [inline legacy/ui/legacy/src/main/java/com/fsck/k9/activity/MessageList.kt:1446]: What happen when we get to this point and the account is still null? Does the NPE just get thrown later?

Are there any assertions or log messages we could add here so that someone with a NPE could provide us more information?

**Review by kewisch — APPROVED** [review]

File: legacy/ui/legacy/src/main/java/com/fsck/k9/activity/MessageList.kt (hunk 1 above)
Comment (wmontwe) [reply legacy/ui/legacy/src/main/java/com/fsck/k9/activity/MessageList.kt:1446]: It will still crash, that was the old behavior. Ideally this code needs to be rewritten without these local states.

Comment (kewisch) [reply legacy/ui/legacy/src/main/java/com/fsck/k9/activity/MessageList.kt:1446]: Can we add some sort of log info that would help us in the case where it still crashes?

Comment (wmontwe) [reply legacy/ui/legacy/src/main/java/com/fsck/k9/activity/MessageList.kt:1446]: Not really, we would need to monitor the changes to the account reference. But the class is complex.

Comment (kewisch) [reply legacy/ui/legacy/src/main/java/com/fsck/k9/activity/MessageList.kt:1446]: Ok, very well. If you have ideas on how we could better monitor this without going overboard I'm open to it, but let's go ahead and merge this.
