### PR TITLE
Fix crash when a swipe action is set to "none"

### LINKED ISSUE #7969: App crashes when a swipe action is set to "none"
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.902

### Where did you get the app from?

Other

### Android version

Grapheneos

### Device model

_No response_

### Steps to reproduce

Open the app.
Crashes.

### Expected behavior

Open without crashing. 

### Actual behavior

Opens, and crashes. 

### Logs

```
type: crash
osVersion: google/husky/husky:14/AP2A.240605.024/2024062000:user/release-keys
package: com.fsck.k9:39002
process: com.fsck.k9
processUptime: 335 + 432 ms
installer: com.android.packageinstaller

java.lang.IllegalStateException: action == SwipeAction.None
	at com.fsck.k9.ui.messagelist.SwipeResourceProvider.getActionColor(SwipeResourceProvider.kt:52)
	at com.fsck.k9.ui.messagelist.SwipeResourceProvider.getActionColorRoles(SwipeResourceProvider.kt:44)
	at com.fsck.k9.ui.messagelist.MessageListSwipeCallback.setupSwipeAction(MessageListSwipeCallback.kt:292)
	at com.fsck.k9.ui.messagelist.MessageListSwipeCallback.<init>(MessageListSwipeCallback.kt:60)
	at com.fsck.k9.ui.messagelist.MessageListFragment.initializeRecyclerView(MessageListFragment.kt:337)
	at com.fsck.k9.ui.messagelist.MessageListFragment.initializeMessageListLayout(MessageListFragment.kt:278)
	at com.fsck.k9.ui.messagelist.MessageListFragment.onViewCreated(MessageListFragment.kt:264)
	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3148)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:600)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:278)
	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:114)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1663)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3247)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3165)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:263)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:350)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:251)
	at com.fsck.k9.activity.MessageList.onStart(MessageList.kt:499)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1706)
	at android.app.Activity.performStart(Activity.java:9056)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4029)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:327)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:307)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleItem(TransactionExecutor.java:279)
	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:150)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:93)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2602)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8623)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
```

### PR DESCRIPTION
**Pull request by cketti**
`SwipeResourceProvider` doesn't expect to be asked to provide resources for `SwipeAction.None` and will throw an exception when that happens. PR #7876 introduced some changes that lead to `SwipeResourceProvider` now being asked to provide resource for `SwipeAction.None` which will result in a crash when displaying the message list.

This changes `MessageListSwipeCallback` to make the old assumption true again; `SwipeResourceProvider` won't be asked to provide resources for `SwipeAction.None`.

Fixes #7969

### CODE REVIEW

File: app/ui/legacy/src/main/java/com/fsck/k9/ui/messagelist/MessageListSwipeCallback.kt [hunk 1]
```diff
@@ -171,7 +171,8 @@ class MessageListSwipeCallback(
     }
 
     private fun Canvas.drawBackground(dX: Float, width: Int, height: Int) {
-        val swipeActionConfig = if (dX > 0) swipeRightConfig else swipeLeftConfig
+        val swipeActionConfig = (if (dX > 0) swipeRightConfig else swipeLeftConfig)
+            ?: error("drawBackground() called despite swipeActionConfig == null")
```
Comment (johnjohndoe) [inline app/ui/legacy/src/main/java/com/fsck/k9/ui/messagelist/MessageListSwipeCallback.kt:175]: These lines could be extracted twice:

``` kotlin
private fun swipeActionConfigOf(swipeRight: Boolean): SwipeActionConfig {
    val config = if (swipeRight) swipeRightConfig else swipeLeftConfig
    return config ?: error("drawBackground() called despite swipeActionConfig == null")
}
```

Also, I find it more readable in two lines.

File: app/ui/legacy/src/main/java/com/fsck/k9/ui/messagelist/MessageListSwipeCallback.kt [hunk 2]
```diff
@@ -288,13 +291,29 @@ class MessageListSwipeCallback(
...
-    private fun setupSwipeAction(swipeAction: SwipeAction, resourceProvider: SwipeResourceProvider) = SwipeActionConfig(
-        colorRoles = resourceProvider.getActionColorRoles(swipeAction),
-        icon = resourceProvider.getActionIcon(swipeAction),
-        iconToggled = resourceProvider.getActionIconToggled(swipeAction),
-        actionName = resourceProvider.getActionName(swipeAction),
-        actionNameToggled = resourceProvider.getActionNameToggled(swipeAction),
-    )
+    private fun isSwipeActionSupported(item: MessageListItem, swipeAction: SwipeAction): Boolean {
+        return when (swipeAction) {
+            SwipeAction.None -> false
```
Comment (johnjohndoe) [inline app/ui/legacy/src/main/java/com/fsck/k9/ui/messagelist/MessageListSwipeCallback.kt:296]: Maybe at least a comment if there is no unit test to avoid this gets refactored in the future again?

File: app/ui/legacy/src/main/res/raw/changelog_master.xml [hunk 3]
```diff
@@ -6,7 +6,7 @@
 -->
 <changelog>
     <release version="6.903" versioncode="39003" date="unreleased">
-        <change>Placeholder</change>
+        <change>Fixed a crash when a message list swipe action was set to "none"</change>
```
Comment (johnjohndoe) [inline app/ui/legacy/src/main/res/raw/changelog_master.xml:9]: `none` -> `None`?

File: app/ui/legacy/src/main/java/com/fsck/k9/ui/messagelist/MessageListSwipeCallback.kt
Comment (johnjohndoe) [inline app/ui/legacy/src/main/java/com/fsck/k9/ui/messagelist/MessageListSwipeCallback.kt:1]: Commit message: Please explain **why** this change is needed.

File: app/ui/legacy/src/main/java/com/fsck/k9/ui/messagelist/MessageListSwipeCallback.kt [hunk 4]
```diff
@@ -288,13 +291,29 @@ class MessageListSwipeCallback(
...
+    ): SwipeActionConfig? {
+        return if (swipeAction == SwipeAction.None) {
+            null
+        } else {
+            SwipeActionConfig(
+                colorRoles = resourceProvider.getActionColorRoles(swipeAction),
+                icon = resourceProvider.getActionIcon(swipeAction),
+                iconToggled = resourceProvider.getActionIconToggled(swipeAction),
+                actionName = resourceProvider.getActionName(swipeAction),
+                actionNameToggled = resourceProvider.getActionNameToggled(swipeAction),
```
Comment (johnjohndoe) [inline app/ui/legacy/src/main/java/com/fsck/k9/ui/messagelist/MessageListSwipeCallback.kt:313]: An option to rewrite:

``` kotlin
with(resourceProvider) {
    SwipeActionConfig(
        colorRoles = getActionColorRoles(swipeAction),
        icon = getActionIcon(swipeAction),
        iconToggled = getActionIconToggled(swipeAction),
        actionName = getActionName(swipeAction),
        actionNameToggled = getActionNameToggled(swipeAction),
    )
}
```

**Review by johnjohndoe — COMMENTED** [review]
Here are my thoughts:

File: app/ui/legacy/src/main/java/com/fsck/k9/ui/messagelist/MessageListSwipeCallback.kt (hunk 2 above)
Comment (cketti) [reply app/ui/legacy/src/main/java/com/fsck/k9/ui/messagelist/MessageListSwipeCallback.kt:296]: Introducing this function is not necessary to fix the crash. I'll remove it to keep this change focused on fixing the immediate cause of the crash.

We'll need to refactor `MessageListSwipeCallback`, `SwipeResourceProvider`, and `SwipeActionSupportProvider` anyway to avoid a problem like this crash in the future.

File: app/ui/legacy/src/main/java/com/fsck/k9/ui/messagelist/MessageListSwipeCallback.kt (hunk 1 above)
Comment (cketti) [reply app/ui/legacy/src/main/java/com/fsck/k9/ui/messagelist/MessageListSwipeCallback.kt]: Moved the error checking to a separate line.

**Review by wmontwe — APPROVED** [review]
This fixes the issue, but I think this implementation needs a makeover. The `SwipeResourceProvider` returns exceptions when called with `SwipeAction.None`, which is suprising for the call side. Also it is totally untested and open for all kinds of failures.

I think the detection of the swipe directions needs to hapen in a separate call and not within the draw methods. That would allow to avoid having to throw 2 times.

File: app/ui/legacy/src/main/java/com/fsck/k9/ui/messagelist/MessageListSwipeCallback.kt (hunk 2 above)
Comment (johnjohndoe) [reply app/ui/legacy/src/main/java/com/fsck/k9/ui/messagelist/MessageListSwipeCallback.kt]: Yes. I thought so two. The function refactoring could be a separate commit at best.
