### PR TITLE
Fix of "QR code import does not update unified inbox"

### LINKED ISSUE #8531: QR code import does not update unified inbox
Follow up on #7556 and #8459

The unified inbox is now disabled by default and only enabled once there are more than 2 accounts. This was changed for the account setup and is missing in the QR code import. We need to ensure that the QR import updates the flag.

### PR DESCRIPTION
**Pull request by shamim-emon**
-  Currently QR import doesn't update Unified inbox value to true if , after importing account , account number > 1.
This PR fixes the issue.

- Fixes #8531

### CODE REVIEW

File: legacy/core/src/main/java/com/fsck/k9/preferences/SettingsImporter.kt [hunk 1]
```diff
@@ -100,6 +103,11 @@ class SettingsImporter internal constructor(
                 }
             }
 
+            if (preferences.getAccounts().size > 1) {
```
Comment (cketti) [inline legacy/core/src/main/java/com/fsck/k9/preferences/SettingsImporter.kt:106]: `SettingsImporter` is not only used for importing QR codes. It's primary use is importing settings files. Those can also include general settings (called "global settings" in the code). If the user imports general settings, we want to use the unified inbox setting from there and not overwrite it. 

So this also has to check if `globalSettingsImported` is `false`.

Comment (shamim-emon) [reply legacy/core/src/main/java/com/fsck/k9/preferences/SettingsImporter.kt]: Done!

File: legacy/core/src/main/java/com/fsck/k9/preferences/SettingsImporter.kt [hunk 2]
```diff
@@ -100,6 +103,11 @@ class SettingsImporter internal constructor(
                 }
             }
 
+            if (preferences.getAccounts().size > 1 && !globalSettingsImported) {
+                K9.isShowUnifiedInbox = true
+                K9.saveSettingsAsync()
+            }
```
Comment (cketti) [inline legacy/core/src/main/java/com/fsck/k9/preferences/SettingsImporter.kt:109]: `AccountCreator` and `SettingsImporter` now contain basically the same code. Since the code also directly references the `K9` object, I think it would be good to extract this code to a separate class.

```kotlin
/**
 * Configures the unified inbox after an account has been added.
 */
class UnifiedInboxConfigurator(
    private val accountManager: AccountManager,
) {
    fun configureUnifiedInbox() {
        if (accountManager.getAccounts().size > 1) {
            K9.isShowUnifiedInbox = true
            K9.saveSettingsAsync()
        }
    }
}
```

This new class can then be used by both `AccountCreator` and `SettingsImporter`.

Comment (shamim-emon) [reply legacy/core/src/main/java/com/fsck/k9/preferences/SettingsImporter.kt]: @cketti Done!

**Comment by shamim-emon** [comment]
> `SettingsImporterTest` should be updated to test if `UnifiedInboxConfigurator` is called (only) when it should be called.

@cketti I've used `mockito ` for added two tests mainly because, I'm not sure how to check `UnifiedInboxConfigurator.configureUnifiedInbox()` is being called or not as it's private to  `SettingsImporter`. 
 
Please let me know if that's alright .
Thanks

**Comment by shamim-emon** [comment]
@cketti @wmontwe fixed the spotless issue. Please allow workflow trigger once more. 
Thanks in advance.

File: legacy/core/src/test/java/com/fsck/k9/preferences/SettingsImporterTest.kt [hunk 3]
```diff
@@ -154,6 +161,101 @@ class SettingsImporterTest : K9RobolectricTest() {
...
+        val settingsImporter = SettingsImporter(
+            settingsFileParser = settingsFileParser,
+            generalSettingsValidator = mock<GeneralSettingsValidator>(),
+            accountSettingsValidator = mock<AccountSettingsValidator>(),
+            generalSettingsUpgrader = mock<GeneralSettingsUpgrader>(),
+            accountSettingsWriter = mock<AccountSettingsWriter>(),
+            accountSettingsUpgrader = mock<AccountSettingsUpgrader>(),
+            generalSettingsWriter = generalSettingsWriter,
+            unifiedInboxConfigurator = unifiedInboxConfigurator,
+        )
```
Comment (cketti) [inline legacy/core/src/test/java/com/fsck/k9/preferences/SettingsImporterTest.kt:179]: This is making the test much more complicated than it needs to be. The only dependency that needs to be replaced is `UnifiedInboxConfigurator`. The rest can be retrieved via Koin.

```kotlin
import org.koin.test.get

val unifiedInboxConfigurator = mock<UnifiedInboxConfigurator>()

val settingsImporter = SettingsImporter(
    settingsFileParser = get(),
    generalSettingsValidator = get(),
    accountSettingsValidator = get(),
    generalSettingsUpgrader = get(),
    accountSettingsWriter = get(),
    accountSettingsUpgrader = get(),
    generalSettingsWriter = get(),
    unifiedInboxConfigurator = unifiedInboxConfigurator,
)
```

Comment (shamim-emon) [reply legacy/core/src/test/java/com/fsck/k9/preferences/SettingsImporterTest.kt]: @cketti Done!

**Review by cketti — APPROVED** [review]
Thanks :+1:
