### PR TITLE
Fixed Bug - Cannot disable New mail notifcations

### LINKED ISSUE #9135: Cannot disable "New mail notifcations" in 11.0b1
### Checklist

- [x] I have used the search function to see if someone else has already submitted the same bug report.
- [x] I will describe the problem with as much detail as possible.

### App

Thunderbird for Android

### App version

11.0b1

### Where did you get the app from?

Play store

### Android version

15

### Device model

Pixel 9 Pro

### Steps to reproduce

* Go to General settings->Select an account->Notifications
* Remove check mark for "New mail notifications"
* Hit back arrow
* Go to Notifications again
* "New mail notifications" contains check mark

### Expected behavior

"New mail notifications" check mark removal should be persistent

### Actual behavior

"New mail notifications" contains check mark after I removed it

### Logs

_No response_

### PR DESCRIPTION
**Pull request by shamim-emon**
- Fixes #9135

### CODE REVIEW

File: legacy/core/src/main/java/com/fsck/k9/preferences/Storage.java [hunk 1]
```diff
@@ -66,4 +66,8 @@ public String getString(String key, String defValue) {
         }
         return val;
     }
+
+    public boolean valueAlreadyExist(String key) {
+        return values.containsKey(key);
+    }
```
Comment (rafaeltonholo) [inline legacy/core/src/main/java/com/fsck/k9/preferences/Storage.java:72]: We already have a method called `contains(key)` that serves the same purpose as the newly introduced method. Please use the existing method instead.

File: legacy/core/src/main/java/com/fsck/k9/AccountPreferenceSerializer.kt [hunk 2]
```diff
@@ -61,13 +63,18 @@ class AccountPreferenceSerializer(
...
                 "$accountUuid.folderNotifyNewMailMode",
                 FolderMode.ALL,
             )
-            isNotifySelfNewMail = storage.getBoolean("$accountUuid.notifySelfNewMail", true)
+            if (storage.valueAlreadyExist("$accountUuid.notifyNewMail")) {
+                isNotifyNewMail = storage.getBoolean("$accountUuid.notifyNewMail", false)
+                isNotifySelfNewMail = storage.getBoolean("$accountUuid.notifySelfNewMail", true)
+            } else {
+                accountDefaultsProvider.applyOverwrites(account = account)
+            }
```
Comment (rafaeltonholo) [inline legacy/core/src/main/java/com/fsck/k9/AccountPreferenceSerializer.kt:76]: While the `applyOverwrites` method currently overrides both `isNotifyNewMail` and `isNotifySelfNewMail`, it is not intended to be limited to these functions. We need to explore alternative solutions for this issue.

**Review by rafaeltonholo — CHANGES_REQUESTED** [review]
Although this solution addresses the issue, I believe it is not the ideal way to handle it. The `AccountDefaultsProvider.applyOverwrites` method is generic and could potentially include other fields in the future, beyond just `isNotifyNewMail` and `isNotifySelfNewMail`.

I suggest exploring a solution where the `applyOverwrites` method checks whether the user has already modified the field it is attempting to override.

File: legacy/core/src/main/java/com/fsck/k9/preferences/Storage.java (hunk 1 above)
Comment (shamim-emon) [reply legacy/core/src/main/java/com/fsck/k9/preferences/Storage.java]: Done

File: legacy/core/src/main/java/com/fsck/k9/AccountPreferenceSerializer.kt (hunk 2 above)
Comment (shamim-emon) [reply legacy/core/src/main/java/com/fsck/k9/AccountPreferenceSerializer.kt]: Added alternate solution
