### PR TITLE
Ignore line breaks in single line text inputs

### LINKED ISSUE #7670: Don't allow passwords containing line breaks
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.717

### Where did you get the app from?

None

### Android version

X

### Device model

_No response_

### Steps to reproduce

Start configuring your icloud.com email

### Expected behavior

Password checks and it goes to next step

I did the setup on FairEmail at the same time and it worked. 

### Actual behavior

Server error: unmatch quote

### Logs

```
02-24 22:58:27.993 20341 10889 V RealImapConnection: conn72600286 <<< #null# [OK, [CAPABILITY, XAPPLEPUSHSERVICE, IMAP4, IMAP4rev1, SASL-IR, AUTH=ATOKEN, AUTH=PLAIN], (2409B40-f42d5d1bd981) mr36p00im-tygg11200301.me.com]
02-24 22:58:27.994 20341 10889 D RealImapConnection: Saving [IMAP4, AUTH=PLAIN, XAPPLEPUSHSERVICE, SASL-IR, AUTH=ATOKEN, IMAP4REV1] capabilities for conn72600286
02-24 22:58:27.995 20341 10889 V RealImapConnection: conn72600286>>> 1 AUTHENTICATE PLAIN 

02-24 22:58:28.166 20341 20341 D InsetsController: show(ime(), fromIme=true)
02-24 22:58:28.223 20341 10889 V RealImapConnection: conn72600286<<<#+# []
02-24 22:58:28.651 20341 10889 V ImapResponseParser: conn72600286<<<#1# [NO, [AUTHENTICATIONFAILED], Authentication Failed]


RealImapConnection: conn72600286>>> 2 LOGIN "myusername" "ykkl-xxx-xxxt-kkki
02-24 22:58:28.655 20341 10889 V RealImapConnection: 
02-24 22:58:28.655 20341 10889 V RealImapConnection: "
02-24 22:58:28.848 20341 10889 V ImapResponseParser: conn72600286<<<#2# [BAD, unmatch quote]
```

### PR DESCRIPTION
**Pull request by cketti**
Fixes #7670

### CODE REVIEW

File: core/ui/compose/designsystem/src/main/kotlin/app/k9mail/core/ui/compose/designsystem/atom/textfield/TextFieldCommon.kt [hunk 1]
```diff
@@ -5,6 +5,24 @@ import androidx.compose.runtime.Composable
 import androidx.compose.ui.tooling.preview.Preview
 import app.k9mail.core.ui.compose.theme.PreviewWithThemes
 
+private val LINE_BREAK = "[\\r\\n]".toRegex()
+
+internal fun fixSingleLineBehavior(isSingleLine: Boolean, onValueChange: (String) -> Unit): (String) -> Unit {
```
Comment (wmontwe) [inline core/ui/compose/designsystem/src/main/kotlin/app/k9mail/core/ui/compose/designsystem/atom/textfield/TextFieldCommon.kt:10]: This could be simplified to:

```suggestion
internal fun fixSingleLineBehavior(isSingleLine: Boolean, onValueChange: (String) -> Unit): (String) -> Unit {
    return { value ->
        if (isSingleLine) {
            onValueChange(value.replace(LINE_BREAK, replacement = ""))
        } else {
            onValueChange(value)
        }
    }
}
```

File: core/ui/compose/designsystem/src/main/kotlin/app/k9mail/core/ui/compose/designsystem/atom/textfield/TextFieldOutlinedEmailAddress.kt [hunk 2]
```diff
@@ -22,7 +22,7 @@ fun TextFieldOutlinedEmailAddress(
 ) {
     MaterialOutlinedTextField(
         value = value,
-        onValueChange = onValueChange,
+        onValueChange = stripLineBreaks(onValueChange),
```
Comment (wmontwe) [inline core/ui/compose/designsystem/src/main/kotlin/app/k9mail/core/ui/compose/designsystem/atom/textfield/TextFieldOutlinedEmailAddress.kt:25]:
```suggestion
        onValueChange = fixSingleLineBehavior(true, onValueChange)
```

File: core/ui/compose/designsystem/src/main/kotlin/app/k9mail/core/ui/compose/designsystem/atom/textfield/TextFieldOutlinedPassword.kt [hunk 3]
```diff
@@ -35,7 +35,7 @@ fun TextFieldOutlinedPassword(
 
     MaterialOutlinedTextField(
         value = value,
-        onValueChange = onValueChange,
+        onValueChange = stripLineBreaks(onValueChange),
```
Comment (wmontwe) [inline core/ui/compose/designsystem/src/main/kotlin/app/k9mail/core/ui/compose/designsystem/atom/textfield/TextFieldOutlinedPassword.kt:38]:
```suggestion
        onValueChange = fixSingleLineBehavior(true, onValueChange)
```

File: core/ui/compose/designsystem/src/main/kotlin/app/k9mail/core/ui/compose/designsystem/atom/textfield/TextFieldOutlinedPassword.kt [hunk 4]
```diff
@@ -70,7 +70,7 @@ fun TextFieldOutlinedPassword(
 ) {
     MaterialOutlinedTextField(
         value = value,
-        onValueChange = onValueChange,
+        onValueChange = stripLineBreaks(onValueChange),
```
Comment (wmontwe) [inline core/ui/compose/designsystem/src/main/kotlin/app/k9mail/core/ui/compose/designsystem/atom/textfield/TextFieldOutlinedPassword.kt:73]:
```suggestion
        onValueChange = fixSingleLineBehavior(true, onValueChange)
```

File: core/ui/compose/designsystem/src/test/kotlin/app/k9mail/core/ui/compose/designsystem/atom/textfield/TextInputTextFieldTest.kt [hunk 5]
```diff
@@ -49,6 +56,23 @@ class TextInputTextFieldTest(
         assertThat(value).isEqualTo("$testInput + added text")
     }
 
+    @Test
+    fun `should strip line breaks before onValueChange is called`() = runComposeTest {
```
Comment (wmontwe) [inline core/ui/compose/designsystem/src/test/kotlin/app/k9mail/core/ui/compose/designsystem/atom/textfield/TextInputTextFieldTest.kt:60]: This is only true when `isSingleLine` is enabled. With this test `TextFieldOutlined` is forces to always strip linebreaks, which is undesired for multiline text input. You added `TextFieldOutlinedKtTest` to compensate for that, but I think using a parameterized test reached a state where it's more a burden than helpful.

File: core/ui/compose/designsystem/src/test/kotlin/app/k9mail/core/ui/compose/designsystem/atom/textfield/TextInputTextFieldTest.kt [hunk 6]
```diff
@@ -60,6 +84,7 @@ class TextInputTextFieldTest(
                     TextFieldOutlined(
                         value = value,
                         onValueChange = onValueChange,
+                        isSingleLine = true,
```
Comment (wmontwe) [inline core/ui/compose/designsystem/src/test/kotlin/app/k9mail/core/ui/compose/designsystem/atom/textfield/TextInputTextFieldTest.kt:87]: I think there should be an additional test case, one with single line enabled and one without.

File: core/ui/compose/designsystem/src/main/kotlin/app/k9mail/core/ui/compose/designsystem/atom/textfield/TextFieldCommon.kt (hunk 1 above)
Comment (cketti) [reply core/ui/compose/designsystem/src/main/kotlin/app/k9mail/core/ui/compose/designsystem/atom/textfield/TextFieldCommon.kt]: I don't like how `isSingleLine` is checked inside the lambda instead of outside. Given that `fixSingleLineBehavior()` was only used once, I decided to move the logic to the call site.

https://github.com/thunderbird/thunderbird-android/blob/9bef2a4b0651f7e219a3ebd94e40b6ac79ddd9de/core/ui/compose/designsystem/src/main/kotlin/app/k9mail/core/ui/compose/designsystem/atom/textfield/TextFieldOutlined.kt#L29

File: core/ui/compose/designsystem/src/test/kotlin/app/k9mail/core/ui/compose/designsystem/atom/textfield/TextInputTextFieldTest.kt (hunk 5 above)
Comment (cketti) [reply core/ui/compose/designsystem/src/test/kotlin/app/k9mail/core/ui/compose/designsystem/atom/textfield/TextInputTextFieldTest.kt]: I deleted `TextInputTextFieldTest` and created test classes for the individual composables.

File: core/ui/compose/designsystem/src/main/kotlin/app/k9mail/core/ui/compose/designsystem/atom/textfield/TextFieldCommon.kt (hunk 1 above)
Comment (wmontwe) [reply core/ui/compose/designsystem/src/main/kotlin/app/k9mail/core/ui/compose/designsystem/atom/textfield/TextFieldCommon.kt]: Fine with me

File: core/ui/compose/designsystem/src/test/kotlin/app/k9mail/core/ui/compose/designsystem/atom/textfield/TextFieldOutlinedPasswordTest.kt [hunk 7]
```diff
@@ -1,20 +1,26 @@
...
 import app.k9mail.core.ui.compose.testing.ComposeTest
 import assertk.assertThat
+import assertk.assertions.isEqualTo
 import assertk.assertions.isTrue
 import org.junit.Test
 
 private const val PASSWORD = "Password input"
+private const val TEST_TAG = "TextFieldOutlinedPassword"
 
-class TextFieldOutlinedPasswordKtTest : ComposeTest() {
```
Comment (wmontwe) [inline core/ui/compose/designsystem/src/test/kotlin/app/k9mail/core/ui/compose/designsystem/atom/textfield/TextFieldOutlinedPasswordTest.kt:17]: The `Kt` in the name is necessary to easily jump from a composable function to it's test using `Command` + `Shift` + `T` (mac). Without it the IDE doesn't find the test.

**Review by wmontwe — APPROVED** [review]
👍
