### PR TITLE
fix(smtp): outlook smtp not authenticating when enterprise or educational accounts

### LINKED ISSUE #9160: outlook.com outgoing server fails when enterprise or educational accounts
#8024 is still happening for @Hanxyz13. Let's find out why.

@Hanxyz13 could you provide the logs here instead?

### PR DESCRIPTION
**Pull request by rafaeltonholo**
Fixes #9160.

### CODE REVIEW

File: mail/protocols/smtp/src/main/java/com/fsck/k9/mail/transport/smtp/SmtpTransport.kt [hunk 1]
```diff
@@ -551,24 +556,57 @@ class SmtpTransport(
...
-            Log.w(negativeResponse, "saslOAuth: failed to authenticate.")
-            if (negativeResponse.replyCode != SMTP_AUTHENTICATION_FAILURE_ERROR_CODE) {
-                throw negativeResponse
+        checkNotNull(oauthTokenProvider) { "No OAuth2TokenProvider available." }
+
+        val users = buildSet {
+            // add the given username to the list of users
+            add(username)
+            // add all the usernames we can fetch from the id_token to be used in case from
+            // the given username is fails to authenticate.
```
Comment (wmontwe) [inline mail/protocols/smtp/src/main/java/com/fsck/k9/mail/transport/smtp/SmtpTransport.kt]:
```suggestion
            // add all the usernames we can fetch from the id_token to be used in case
            // the given username fails to authenticate.
```

File: mail/protocols/smtp/src/main/java/com/fsck/k9/mail/transport/smtp/SmtpTransport.kt [hunk 2]
```diff
@@ -551,24 +556,57 @@ class SmtpTransport(
...
+                break
+            } catch (negativeResponse: NegativeSmtpReplyException) {
+                Log.w(negativeResponse, "saslOAuth: failed to authenticate.")
+                if (negativeResponse.replyCode != SMTP_AUTHENTICATION_FAILURE_ERROR_CODE) {
+                    throw negativeResponse
+                }
+                iterator.remove()
+                negativeResponses += user to negativeResponse
             }
+        }
```
Comment (wmontwe) [inline mail/protocols/smtp/src/main/java/com/fsck/k9/mail/transport/smtp/SmtpTransport.kt:619]: This could be a separate method:

```suggestion
        val negativeResponses = authenticateUsers(method, users)
```

and

```kotlin
private fun authenticateUsers(
    method: OAuthMethod,
    users: MutableSet<String>
): Map<String, NegativeSmtpReplyException> {
    val negativeResponses = mutableMapOf<String, NegativeSmtpReplyException>()
    val sensitiveLog = "*sensitive*"
    logger.log("users = ${users.takeIf { K9MailLib.isDebugSensitive() } ?: "[${users.size} emails found]"}")


    val iterator = users.iterator()
    while (iterator.hasNext()) {
        val user = iterator.next()
        try {
            logger.log(
                "trying to authenticate with user '${
                    user.takeIf { K9MailLib.isDebugSensitive() } ?: sensitiveLog
                }'",
            )
            attempOAuth(method, user)
            negativeResponses.clear()
            break
        } catch (negativeResponse: NegativeSmtpReplyException) {
            Log.w(negativeResponse, "saslOAuth: failed to authenticate.")
            if (negativeResponse.replyCode != SMTP_AUTHENTICATION_FAILURE_ERROR_CODE) {
                throw negativeResponse
            }
            iterator.remove()
            negativeResponses += user to negativeResponse
        }
    }
    return negativeResponses
}
```

**Review by wmontwe — COMMENTED** [review]
I think the method could be split for better readability.

**Review by wmontwe — APPROVED** [review]
LGTM
