### PR TITLE
Change default value for "Fetch messages up to" to 128KiB

### LINKED ISSUE #7892: Increase default value for "Fetch messages up to"
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.901

### Where did you get the app from?

Google Play

### Android version

14

### Device model

Pixel 8 Pro

### Steps to reproduce

I received an email from Uber just now and I'm like WTF? So I open the email, scroll to the bottom looking for the unsubscribe link and its not there, instead I see a download full message email. Huh? I'm confused as to what the reasoning for not giving full emails is? 

### Expected behavior

Full emails should be fetched by default. If anything there should be a preference for a minimalist broken experience. 

### Actual behavior

Not even being able to unsubscribe from uber emails because I can't see the bottom of the email. 

### Logs

_No response_

### PR DESCRIPTION
**Pull request by cketti**
Closes #7892

### CODE REVIEW

File: app/core/src/main/java/com/fsck/k9/AccountPreferenceSerializer.kt [hunk 1]
```diff
@@ -597,7 +598,7 @@ class AccountPreferenceSerializer(
             maxPushFolders = 10
             isSubscribedFoldersOnly = false
             maximumPolledMessageAge = -1
-            maximumAutoDownloadMessageSize = 32768
+            maximumAutoDownloadMessageSize = 131072
```
Comment (wmontwe) [inline app/core/src/main/java/com/fsck/k9/AccountPreferenceSerializer.kt:601]: Consider using a constant for the default value of `maximumAutoDownloadMessageSize`. Then there is no need to suppress `MagicNumber`.

File: app/core/src/main/java/com/fsck/k9/AccountPreferenceSerializer.kt [hunk 2]
```diff
@@ -124,7 +125,7 @@ class AccountPreferenceSerializer(
             maxPushFolders = storage.getInt("$accountUuid.maxPushFolders", 10)
             isSubscribedFoldersOnly = storage.getBoolean("$accountUuid.subscribedFoldersOnly", false)
             maximumPolledMessageAge = storage.getInt("$accountUuid.maximumPolledMessageAge", -1)
-            maximumAutoDownloadMessageSize = storage.getInt("$accountUuid.maximumAutoDownloadMessageSize", 32768)
+            maximumAutoDownloadMessageSize = storage.getInt("$accountUuid.maximumAutoDownloadMessageSize", 131072)
```
Comment (wmontwe) [inline app/core/src/main/java/com/fsck/k9/AccountPreferenceSerializer.kt:128]: Consider using a constant for the default value of `maximumAutoDownloadMessageSize`. Then there is no need to suppress `MagicNumber`.

**Review by wmontwe — APPROVED** [review]
👍
