### PR TITLE
Remove font size customization

### LINKED ISSUE #8949: Remove font size customization
As per #8420 we're considering to remove the font size customization and replace it with some more specific options to choose what the emphasis is. The font size selection is also broken in many ways, so it isn't quite as useful.

The removing bit would be a good first bug, and then we can do a follow up with design if someone is eager to follow on.

Please make sure to use feature flags for this, we'd definitely want to test this on beta for a while before we ship this to the majority of users.

### PR DESCRIPTION
**Pull request by shamim-emon**
- Fixes #8949

### CODE REVIEW

File: legacy/core/src/main/java/com/fsck/k9/K9.kt [hunk 1]
```diff
@@ -383,7 +388,15 @@ object K9 : KoinComponent {
...
-        fontSizes.load(storage)
+
+        val disableFontSizeConfig = when (featureFlagProvider.provide("disable_font_size_config".toFeatureFlagKey())) {
+            FeatureFlagResult.Enabled -> true
+            FeatureFlagResult.Disabled -> false
+            FeatureFlagResult.Unavailable -> false
+        }
+        if (!disableFontSizeConfig) {
+            fontSizes.load(storage)
+        }
```
Comment (wmontwe) [inline legacy/core/src/main/java/com/fsck/k9/K9.kt:399]: This could be

```suggestion
        featureFlagProvider.provide("disable_font_size_config".toFeatureFlagKey())
            .onDisabledOrUnavailable {
                fontSizes.load(storage)
            }
```

File: legacy/core/src/test/java/com/fsck/k9/TestApp.kt [hunk 2]
```diff
@@ -44,4 +48,13 @@ val testModule = module {
     single { mock<NotificationStrategy>() }
     single(named("controllerExtensions")) { emptyList<ControllerExtension>() }
     single { mock<WorkManager>() }
+    single<FeatureFlagProvider> {
+        InMemoryFeatureFlagProvider(
+            featureFlagFactory = {
+                listOf(
+                    FeatureFlag(key = FeatureFlagKey("feature1"), enabled = true),
+                )
```
Comment (wmontwe) [inline legacy/core/src/test/java/com/fsck/k9/TestApp.kt:56]: I think an emptyList should be enough.

```suggestion
                emptyList<FeatureFlag>()
```

File: legacy/ui/legacy/src/main/java/com/fsck/k9/ui/settings/general/GeneralSettingsFragment.kt [hunk 3]
```diff
@@ -37,6 +43,21 @@ class GeneralSettingsFragment : PreferenceFragmentCompat() {
...
+        }
+
+        if (disableFontSizeConfig) {
+            val parentPreference = findPreference<PreferenceCategory>("global_preferences")
+            val fontSizePreferenceScreen = findPreference<PreferenceScreen>("font_size")
+
+            if (parentPreference != null && fontSizePreferenceScreen != null) {
+                parentPreference.removePreference(fontSizePreferenceScreen)
+            }
+        }
```
Comment (wmontwe) [inline legacy/ui/legacy/src/main/java/com/fsck/k9/ui/settings/general/GeneralSettingsFragment.kt:59]: Could be replaced by:

```suggestion
        featureFlagProvider.provide("disable_font_size_config".toFeatureFlagKey())
            .onEnabled {
                val parentPreference = findPreference<PreferenceCategory>("global_preferences")
                val fontSizePreferenceScreen = findPreference<PreferenceScreen>("font_size")

                if (parentPreference != null && fontSizePreferenceScreen != null) {
                    parentPreference.removePreference(fontSizePreferenceScreen)
                }
            }
```

**Review by wmontwe — CHANGES_REQUESTED** [review]
Thanks, the `FeatureFlagResult` has methods to simplify handling, like `onEnabled` and `onDisabledOrUnavailable`.

Also there is no need to do so many commits, the changes are all related to adding the feature flag and should be one.

**Comment by wmontwe** [comment]
@shamim-emon I added a git commit guide, please have a look and comments are welcome.

**Comment by shamim-emon** [comment]
> Thanks, the `FeatureFlagResult` has methods to simplify handling, like `onEnabled` and `onDisabledOrUnavailable`.
> 
> Also there is no need to do so many commits, the changes are all related to adding the feature flag and should be one.
> 
> We aim to group related changes into a commit and split them up when the change is to big or touches different aspects of the source code. Additionally, commits could be used to help the reviewer or whoever retroactively looks into the changes to understand how an existing functionality was changed to new behaviour.

@wmontwe Updated accordingly

**Comment by wmontwe** [comment]
@shamim-emon Just one last thing, rebase your changes on main instead of merging them into your branch, please.

**Comment by wmontwe** [comment]
Thanks, just the debug flags are missing.

**Comment by shamim-emon** [comment]
> @shamim-emon Just some last things, rebase your changes on main instead of merging them into your branch, please. The second commit should be named after what it's changing. In this case: `remove unused properties from K9 class`.
> 
> The the flag should be set for K-9 debug, Thunderbird debug, daily and beta.

@wmontwe Done

**Review by wmontwe — APPROVED** [review]
Thank you!
