### PR TITLE
Bug: Unified Folder Not Showing And Navigation Drawer Selected Item Appearance Not Changing

### LINKED ISSUE #9105: Navigation Drawer Unified Inbox Not Shown And Navigation Item Selection Appearance Issue
### Checklist

- [x] I have used the search function to see if someone else has already submitted the same bug report.
- [x] I will describe the problem with as much detail as possible.

### App

Thunderbird for Android

### App version

12.0-SNAPSHOT

### Where did you get the app from?

None

### Android version

16

### Device model

Pixel 8 Pro

### Steps to reproduce

1. Open The App
2. Open Navigation Drawer
3. Select Settings Gear Icon
4. Select General Settings
5. Select Display
6. Check `Show Unified inbox` under `Account list` section
7. Go Back To Home And Open Navigation Drawer.
8. Unified Inbox Is Not Shown.
9. Also If You Select Any Item From Drawer (Ex: Inbox), Selected Item's Appearance Remains Same As Before, As If It's Not Selected.

https://github.com/user-attachments/assets/601d180f-1051-4f28-a3e5-07f69a1691cc

### Expected behavior

1. Unified Inbox Should Be Visible
2.  Selected Navigation Item/Folder Should Have Selected Appearance, Upon Selection. 

### Actual behavior

1. Unified Inbox Is Not Shown.
2. If You Select Any Item From Drawer (Ex: Inbox), Selected Item's Appearance Remains Same As Before, As If It's Not Selected.

### Logs

_No response_

### PR DESCRIPTION
**Pull request by shamim-emon**
- Fixes #9105

### CODE REVIEW

File: feature/navigation/drawer/dropdown/src/main/kotlin/net/thunderbird/feature/navigation/drawer/dropdown/ui/folder/FolderList.kt [hunk 1]
```diff
@@ -41,16 +40,19 @@ internal fun FolderList(
...
-                    onClick = onFolderClick,
-                    folderNameFormatter = folderNameFormatter,
-                )
-            }
+            FolderListItem(
+                displayFolder = currentDisplayFolder ?: run {
+                    throw NullPointerException(
+                        "Null DisplayFolder for folder ${folder.displayName}",
+                    )
+                },
```
Comment (rafaeltonholo) [inline feature/navigation/drawer/dropdown/src/main/kotlin/net/thunderbird/feature/navigation/drawer/dropdown/ui/folder/FolderList.kt:48]: Could you please use `requireNotNull` instead of throwing `NullPointerException`?
```suggestion
                displayFolder = requireNotNull(currentDisplayFolder) {
                    "Null DisplayFolder for folder ${folder.displayName}"
                },
```

File: feature/navigation/drawer/dropdown/src/main/kotlin/net/thunderbird/feature/navigation/drawer/dropdown/ui/folder/FolderListItem.kt [hunk 2]
```diff
@@ -88,7 +89,7 @@ internal fun FolderListItem(
             if (displayChild === null) continue
             FolderListItem(
                 displayFolder = displayChild,
-                selected = false,
+                selected = selectedFolderId?.let { displayChild.id == selectedFolderId } ?: false,
```
Comment (rafaeltonholo) [inline feature/navigation/drawer/dropdown/src/main/kotlin/net/thunderbird/feature/navigation/drawer/dropdown/ui/folder/FolderListItem.kt:92]: You can use equality check can be used instead of elvis for nullable boolean check:
```suggestion
                selected = selectedFolderId?.let { displayChild.id == selectedFolderId } == true,
```

**Review by rafaeltonholo — APPROVED** [review]
LGTM, thanks for another contribution! 😄 🎉

**Comment by ramonagavrilescu** [comment]
We have checked this request on TB Android 11.0b2, we have updated the app from google play.
We have tested on multiple devices Samsung Galaxy Tab9(Android14), Samsung Galaxy Fold 4(Android15) , Pixel 7(Android14) OPPO A58(Android 13).
After the Show Unified Inbox is checked the Unified inbox appears.
