### PR TITLE
Fix server settings where username or password contains line break

### LINKED ISSUE #7855: Last update crashes when starting the app
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.901

### Where did you get the app from?

Google Play

### Android version

14

### Device model

Poco F5

### Steps to reproduce

After the update I try to open the app

### Expected behavior

Open the app and check my mail

### Actual behavior

The app crashes and doesn't start.

### Logs

Screenshot_2024-05-18-23-17-58-480_com miui bugreport
Screenshot_2024-05-18-23-18-06-220_com miui bugreport

### PR DESCRIPTION
**Pull request by cketti**
See https://github.com/thunderbird/thunderbird-android/issues/7855#issuecomment-2139379998 for steps on how to reproduce the crash.

Fixes #7855

### CODE REVIEW

File: app/storage/src/main/java/com/fsck/k9/preferences/migrations/DefaultStorageMigrationsHelper.kt [hunk 1]
```diff
@@ -0,0 +1,82 @@
+package com.fsck.k9.preferences.migrations
+
+import android.database.sqlite.SQLiteDatabase
+import androidx.core.content.contentValuesOf
+import app.k9mail.core.android.common.database.getStringOrThrow
+import app.k9mail.core.android.common.database.map
+import timber.log.Timber
+
+class DefaultStorageMigrationsHelper : StorageMigrationsHelper {
```
Comment (wmontwe) [inline app/storage/src/main/java/com/fsck/k9/preferences/migrations/DefaultStorageMigrationsHelper.kt:9]: I noticed that the plural form is used for `Migrations`. Also the package names are in plural form. I think we should use the singular form for package **_names_** and **_classes_**.

File: app/storage/src/main/java/com/fsck/k9/preferences/migrations/StorageMigrationTo22.kt [hunk 2]
```diff
@@ -0,0 +1,76 @@
...
+        for (accountUuid in accountUuids) {
+            fixServerSettings(accountUuid)
+        }
+    }
+
+    private fun fixServerSettings(accountUuid: String) {
+        val incomingServerSettingsJson = migrationsHelper.readValue(db, "$accountUuid.incomingServerSettings") ?: return
+        val outgoingServerSettingsJson = migrationsHelper.readValue(db, "$accountUuid.outgoingServerSettings") ?: return
+
+        val moshi = Moshi.Builder().build()
```
Comment (wmontwe) [inline app/storage/src/main/java/com/fsck/k9/preferences/migrations/StorageMigrationTo22.kt:30]: This could be a separate method to create the adapter.

File: app/storage/src/main/java/com/fsck/k9/preferences/migrations/StorageMigrationTo22.kt [hunk 3]
```diff
@@ -0,0 +1,76 @@
...
+import com.squareup.moshi.Types
+
+/**
+ * Fix server settings by removing line breaks from username and password.
+ */
+class StorageMigrationTo22(
+    private val db: SQLiteDatabase,
+    private val migrationsHelper: StorageMigrationsHelper,
+) {
+    fun fixServerSettings() {
```
Comment (wmontwe) [inline app/storage/src/main/java/com/fsck/k9/preferences/migrations/StorageMigrationTo22.kt:14]: `fixServerSettings` could be found 3 times in this class. I think they should have distinct names to improve readability.

File: app/storage/src/main/java/com/fsck/k9/preferences/migrations/StorageMigrationTo22.kt [hunk 4]
```diff
@@ -0,0 +1,76 @@
...
+
+        val oldOutgoingServerSettings = adapter.fromJson(outgoingServerSettingsJson)
+        if (oldOutgoingServerSettings != null) {
+            val newOutgoingServerSettings = fixServerSettings(oldOutgoingServerSettings)
+            if (newOutgoingServerSettings != null) {
+                val json = adapter.toJson(newOutgoingServerSettings)
+                migrationsHelper.writeValue(db, "$accountUuid.outgoingServerSettings", json)
+            }
+        }
+    }
```
Comment (wmontwe) [inline app/storage/src/main/java/com/fsck/k9/preferences/migrations/StorageMigrationTo22.kt:52]:
```suggestion
        adapter.fromJson(outgoingServerSettingsJson)?.let { settings ->
            fixServerSettings(settings)?.let { newSettings ->
                val json = adapter.toJson(newSettings)
                migrationsHelper.writeValue(db, "$accountUuid.outgoingServerSettings", json)
            }
        }
```

File: app/storage/src/main/java/com/fsck/k9/preferences/migrations/StorageMigrationTo22.kt [hunk 5]
```diff
@@ -0,0 +1,76 @@
...
+        ).serializeNulls()
+
+        val oldIncomingServerSettings = adapter.fromJson(incomingServerSettingsJson)
+        if (oldIncomingServerSettings != null) {
+            val newIncomingServerSettings = fixServerSettings(oldIncomingServerSettings)
+            if (newIncomingServerSettings != null) {
+                val json = adapter.toJson(newIncomingServerSettings)
+                migrationsHelper.writeValue(db, "$accountUuid.incomingServerSettings", json)
+            }
+        }
```
Comment (wmontwe) [inline app/storage/src/main/java/com/fsck/k9/preferences/migrations/StorageMigrationTo22.kt:42]: This could be more idiomatic:

```suggestion
        adapter.fromJson(incomingServerSettingsJson)?.let { settings ->
            fixServerSettings(settings)?.let { newSettings ->
                val json = adapter.toJson(newSettings)
                migrationsHelper.writeValue(db, "$accountUuid.incomingServerSettings", json)
            }
        }
```

File: app/storage/src/main/java/com/fsck/k9/preferences/migrations/StorageMigrationTo22.kt [hunk 6]
```diff
@@ -0,0 +1,76 @@
...
+            return
+        }
+
+        val accountUuids = accountUuidsListValue.split(",")
+        for (accountUuid in accountUuids) {
+            fixServerSettings(accountUuid)
+        }
+    }
+
+    private fun fixServerSettings(accountUuid: String) {
```
Comment (wmontwe) [inline app/storage/src/main/java/com/fsck/k9/preferences/migrations/StorageMigrationTo22.kt:26]: `fixServerSettings` same name different responsibility.

File: app/storage/src/main/java/com/fsck/k9/preferences/migrations/StorageMigrationTo22.kt [hunk 7]
```diff
@@ -0,0 +1,76 @@
...
+        if (oldOutgoingServerSettings != null) {
+            val newOutgoingServerSettings = fixServerSettings(oldOutgoingServerSettings)
+            if (newOutgoingServerSettings != null) {
+                val json = adapter.toJson(newOutgoingServerSettings)
+                migrationsHelper.writeValue(db, "$accountUuid.outgoingServerSettings", json)
+            }
+        }
+    }
+
+    private fun fixServerSettings(serverSettings: Map<String, Any?>): Map<String, Any?>? {
```
Comment (wmontwe) [inline app/storage/src/main/java/com/fsck/k9/preferences/migrations/StorageMigrationTo22.kt:54]: `fixServerSettings` same name different responsibility.

File: app/storage/src/main/java/com/fsck/k9/preferences/K9StoragePersister.java [hunk 8]
```diff
@@ -13,18 +12,18 @@
...
 import timber.log.Timber;
 
 
 public class K9StoragePersister implements StoragePersister {
-    private static final int DB_VERSION = 21;
+    private static final int DB_VERSION = 22;
     private static final String DB_NAME = "preferences_storage";
 
     private final Context context;
+    private final StorageMigrationsHelper migrationsHelper = new DefaultStorageMigrationsHelper();
```
Comment (wmontwe) [inline app/storage/src/main/java/com/fsck/k9/preferences/K9StoragePersister.java:26]: 👍

**Review by wmontwe — APPROVED** [review]
Nice fix. Just left some comments for improvements.

File: app/storage/src/main/java/com/fsck/k9/preferences/migrations/DefaultStorageMigrationsHelper.kt (hunk 1 above)
Comment (cketti) [reply app/storage/src/main/java/com/fsck/k9/preferences/migrations/DefaultStorageMigrationsHelper.kt:9]: I created a separate PR for this. See #7899.
